import type {
  EnemyData,
  EnemyType,
  EnemyTrait,
  EnemyCategory,
  EnemyAbilityType,
  MapTheme,
} from "../types";

// Enemy data with visual properties
// Categories: academic, campus, ranged, flying, boss, nature, swarm
export const ENEMY_DATA: Record<EnemyType, EnemyData> = {
  // =============================================================================
  // ACADEMIC ENEMIES - Academic progression and milestones
  // =============================================================================
  frosh: {
    armor: 0,
    bounty: 12,
    category: "academic",
    color: "#4ade80",
    desc: "눈이 휘둥그레지고 압도당해버린 신입생들은 혼란스러운 물결처럼 Princeton의 정문으로 비틀거리며 들어온다. 개개로는 연약하지만 끊임없는 숫자로 밀어붙이며, 그 압도적인 물량으로 길을 막는다. 당황한 기운 덕분에 보기보다 더 빠르다.",
    flying: false,
    hp: 185,
    name: "글쓰기 세미나",
    size: 20,
    speed: 0.38,
    traits: [],
    troopDamage: 15,
  },
  sophomore: {
    abilities: [
      {
        chance: 0.15,
        desc: "짓누르는 절망으로 병사들의 속도를 늦춘다",
        duration: 2000,
        intensity: 0.2,
        name: "의욕 저하",
        type: "slow",
      },
    ],
    armor: 0.1,
    bounty: 18,
    category: "academic",
    color: "#60a5fa",
    desc: "중간고사와 임포스터 증후군의 잔인한 현실에 짓눌린 2학년들은 어두운 결의를 안고 앞으로 나아간다. 무거운 발걸음이 땅을 울리고, 존재적 공포의 오라는 근처 수비수들의 사기를 갉아먹는다. 신입생 버전보다 확실히 더 질기다.",
    flying: false,
    hp: 345,
    name: "2학년 침체기",
    size: 22,
    speed: 0.32,
    traits: ["armored"],
    troopDamage: 32,
  },
  junior: {
    abilities: [
      {
        chance: 1,
        desc: "주변 타워의 정신을 흐려 피해량을 줄인다",
        duration: 3000,
        intensity: 0.15,
        name: "뇌 안개",
        radius: 100,
        type: "tower_weaken",
      },
    ],
    armor: 0.2,
    bounty: 30,
    category: "academic",
    color: "#c084fc",
    desc: "3학년 독립연구를 겪으며 이들은 집요하고 질긴 적으로 단련되었다. Princeton의 2년을 버틴 자신감을 걸고 걸으며, 학술적 혼란의 안개를 뿜어 수비대의 조준을 흐린다. 후열에 닿기 전에 우선 처리하라.",
    flying: false,
    hp: 630,
    name: "3학년 논문",
    size: 24,
    speed: 0.3,
    traits: ["armored"],
    troopDamage: 48,
  },
  senior: {
    abilities: [
      {
        chance: 0.2,
        desc: "압도적인 지식으로 수비수들을 기절시킨다",
        duration: 1500,
        name: "논문답변",
        type: "stun",
      },
    ],
    armor: 0.3,
    bounty: 50,
    category: "academic",
    color: "#f472b6",
    desc: "논문答辩으로 단련된 전투 베테랑, 4학년은 4년간 쌓인 지식의 빛에 둘러싸인 거대한 학술적 괴물이다. 느리게 움직이지만 엄청난 양의 피해를 흡수하며, 논문答辩의 오라는 근처 타워를 침묵에 빠뜨린다. 학기별 물결의 진정한 최종 보스다.",
    flying: false,
    hp: 1050,
    isBoss: true,
    liveCost: 3,
    name: "학부 논문",
    size: 28,
    speed: 0.24,
    traits: ["armored", "boss"],
    troopDamage: 182,
  },
  gradstudent: {
    abilities: [
      {
        chance: 0.25,
        desc: "존재적 공포를 부여해 지속 피해를 입힌다",
        duration: 4000,
        intensity: 12,
        name: "영혼 흡수",
        type: "poison",
      },
    ],
    armor: 0.3,
    bounty: 75,
    category: "academic",
    color: "#fb923c",
    desc: "대학원생들은 천재성과 광기 사이의 미묘한 경계에 존재하며, 오직 카페인과 망상만으로 버틴다. 텅 빈 눈에서 뿜어져 나오는 존재적 공포가 수비수에게 지속 피해를 입히고, 수년간의 괜히된 연구는 그들을 소름 끼칠 정도로 질기게 만들었다. 그들은 이미 모든 것을 잃었다 — 두려울 것이 남아 있지 않다.",
    flying: false,
    hp: 1540,
    isBoss: true,
    liveCost: 4,
    name: "대학원 지원서",
    size: 30,
    speed: 0.2,
    traits: ["armored", "boss"],
    troopDamage: 238,
  },
  professor: {
    abilities: [
      {
        chance: 1,
        desc: "관료적 절차로 타워 공격 속도를 늦춘다",
        duration: 4000,
        intensity: 0.35,
        name: "관료주의",
        radius: 120,
        type: "tower_slow",
      },
      {
        chance: 0.2,
        desc: "수비수들을 기습해서 기절시킨다",
        duration: 1200,
        name: "돌발 퀴즈",
        type: "stun",
      },
    ],
    armor: 0.4,
    bounty: 100,
    category: "academic",
    color: "#ef4444",
    desc: "종신 tenure를 받고 건드릴 수 없게 된 교수들은 학술 관료제와 제도적 관성의 두터운 층에 감싸여 캠퍼스를 거닌다. 시들어버리는 강의는 타워의 공격 속도를 늦추고, 깜짝 팝 퀴즈 기습은 준비되지 않은 자를 기절시킨다. 한 명을 처치하려면 지속적이고 집중된 화력이 필요하다.",
    flying: false,
    hp: 2420,
    isBoss: true,
    liveCost: 5,
    name: "종신 교수",
    size: 32,
    speed: 0.16,
    traits: ["armored", "boss", "tower_debuffer"],
    troopDamage: 308,
  },
  dean: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 8000,
        desc: "타워를 일시적으로 완전히 무력화한다",
        duration: 3500,
        name: "행정보류",
        radius: 100,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "서류 더미로 수비수들을 묻어 느리게 만든다",
        duration: 3500,
        intensity: 0.45,
        name: "서류 작업",
        type: "slow",
      },
    ],
    armor: 0.45,
    bounty: 150,
    category: "academic",
    color: "#a855f7",
    desc: "대학 관료제의 살아서 걷는 요새인 학장은 절대적인 행정 권한을 장악하고 있다. 단 한 번의 공문으로 타워를 완전히 무력화하고, 서류 더미 산더미로 수비수들을 기어가는 속도까지 늦출 수 있다. 가장 강력한 방어만이 위원회 승인 갑옷을 뚫을 수 있다.",
    flying: false,
    hp: 3850,
    isBoss: true,
    liveCost: 6,
    name: "학장",
    size: 36,
    speed: 0.15,
    traits: ["armored", "boss", "tower_debuffer"],
    troopDamage: 392,
  },
  trustee: {
    abilities: [
      {
        chance: 1,
        desc: "모든 타워의 효과를 일률적으로 약화시킨다",
        duration: 5000,
        intensity: 0.3,
        name: "예산 삭감",
        radius: 150,
        type: "tower_weaken",
      },
      {
        chance: 0.25,
        desc: "불타는 명령서를 내리며 지속 피해를 입힌다",
        duration: 4500,
        intensity: 20,
        name: "맹렬한 칙령",
        type: "burn",
      },
    ],
    aoeDamage: 308,
    aoeRadius: 90,
    armor: 0.4,
    bounty: 300,
    category: "campus",
    color: "#eab308",
    desc: "Princeton의 왕좌 뒤에 있는 궁극의 권력, 이사회는 세대에 걸친 부가 뒷받침되는 거의 무한한 제도적 권한을 휘두른다. 예산 명령은 모든 타워의 효과를 일률적으로 깎아내리고, 타오르는 기금 포고령은 끊임없는 피해를 입힌다. 사실상 움직일 수 없다 — 그들에 맞서지 말고 그들을 피해 방어를 설계하라.",
    flying: false,
    hp: 8250,
    isBoss: true,
    liveCost: 10,
    name: "이사회",
    size: 42,
    speed: 0.12,
    traits: ["armored", "boss", "tower_debuffer", "aoe_attack"],
    troopDamage: 504,
  },
  // =============================================================================
  // FLYING ENEMIES
  // =============================================================================
  mascot: {
    armor: 0,
    bounty: 60,
    category: "flying",
    color: "#22d3d3",
    desc: "라이벌 학교 마스코들이 적색과 파란색의 흐릿함과 참을 수 없을 학교 정신을 뽐내며 전장을 가로질러 윙윙거린다. 너무 빠르고 불규칙해서 안정적으로 조준할 수 없으며, 타워 사이를 비껴다니며 싸우지 않는다. 광역 방어를 쓰거나 그냥 보내라 — 위협이라기보다 성가심이다.",
    flying: true,
    hp: 520,
    name: "라이벌 마스코트",
    size: 26,
    speed: 0.53,
    traits: ["flying", "fast", "breakthrough"],
  },
  // =============================================================================
  // RANGED ENEMIES
  // =============================================================================
  archer: {
    armor: 0.1,
    attackSpeed: 2200,
    bounty: 25,
    category: "ranged",
    color: "#10b981",
    desc: "놀라울 정도로 정확한 규정 집행 석궁으로 무장한 캠퍼스 안전 요원들. 전열 뒤에서 물러나 있다가 멀리서부터 타워에 단속 화살을 퍼붓는다. 지역별 변형형은 그 지방의 집행 전통에 맞춰 유니폼과 무기를 바꾼다.",
    flying: false,
    hp: 290,
    isRanged: true,
    name: "P-레이드 마샬",
    projectileDamage: 45,
    range: 220,
    size: 22,
    speed: 0.3,
    traits: ["ranged"],
  },
  mage: {
    abilities: [
      {
        chance: 0.3,
        desc: "휘발성 화학물질로 화상 피해를 입힌다",
        duration: 3000,
        intensity: 12,
        name: "화학 화상",
        type: "burn",
      },
    ],
    armor: 0.15,
    attackSpeed: 2800,
    bounty: 55,
    category: "ranged",
    color: "#8b5cf6",
    desc: "불량해진 화학실험실 조교들이 휘발성 유기 플라스크를 던지며, 그것이 깨져 시약 불길의 화상 연못이 된다. 지속 피해를 주는 공격을 퍼붓고, 수년간 위험물질을 다루어온 덕에 의외로 질기다. 지역마다 그 지방의 재료로 연금술 무장을 바꾼다.",
    flying: false,
    hp: 400,
    isRanged: true,
    name: "Pre-Med Student",
    projectileDamage: 80,
    range: 180,
    size: 24,
    speed: 0.22,
    traits: ["ranged", "magic_resist"],
  },
  catapult: {
    aoeDamage: 150,
    aoeRadius: 70,
    armor: 0.4,
    attackSpeed: 4500,
    bounty: 90,
    category: "ranged",
    color: "#854d0e",
    desc: "극한 사거리에서 학술적 기대의 압도적인 무게를 내던지는 거대한 공성 병기. 느리지만 두꺼운 갑옷을 두르고, 집결된 방어를 압도하는 광역 피해를 입힌다. 타워 배치를 신중히 하라 — 이들의 포격 궤적은 광대한 범위를 덮는다.",
    flying: false,
    hp: 1100,
    isRanged: true,
    liveCost: 2,
    name: "대학원 지원서",
    projectileDamage: 175,
    range: 240,
    size: 34,
    speed: 0.14,
    traits: ["ranged", "armored", "aoe_attack"],
  },
  warlock: {
    abilities: [
      {
        chance: 1,
        desc: "타워를 현란하게 만들어 사거리를 줄인다",
        duration: 4000,
        intensity: 0.2,
        name: "False Promises",
        radius: 100,
        type: "tower_blind",
      },
      {
        chance: 0.15,
        desc: "수비수들의 생명력을 빼앗는다",
        duration: 3000,
        intensity: 10,
        name: "Soul Siphon",
        type: "poison",
      },
    ],
    armor: 0.2,
    attackSpeed: 2400,
    bounty: 70,
    category: "ranged",
    color: "#4c1d95",
    desc: "여섯 자리 수의 서명 보너스로 수비수들을 자리에서 유혹해 끌어내는 기업 설득의 흑마법을 부리는 월거리 리크루터들. 채용 오라는 타워의 사거리를 줄이고, 영혼 흡착 공격은 너무 오래 듣는 자의 생명력을 빼앗는다. 지역 변형은 지방 산업의 색깔과 계약을 갖추고 있다.",
    flying: false,
    hp: 500,
    isRanged: true,
    name: "Job Recruiter",
    projectileDamage: 100,
    range: 180,
    size: 28,
    speed: 0.2,
    traits: ["ranged", "tower_debuffer"],
  },
  crossbowman: {
    abilities: [
      {
        chance: 1,
        desc: "강력한 볼트가 명중 시 대상을 기절시킨다",
        duration: 800,
        name: "Heavy Bolt",
        type: "stun",
      },
    ],
    armor: 0.35,
    attackSpeed: 3500,
    bounty: 50,
    category: "ranged",
    color: "#78350f",
    desc: "강력한 석궁으로 방어를 뚫는 무거운 갑옷의 캠퍼스 보안 베테랑. 볼트는 명중 시 기절시키고, 전술 갑옷은 일반 원거리 위협보다 훨씬 질기다. 화산 지역에서는 볼트 끝이 과열되어 빛나고, 겨울에는 얼음 파편으로 부서진다.",
    flying: false,
    hp: 600,
    isRanged: true,
    name: "Eating Club Bouncer",
    projectileDamage: 95,
    range: 200,
    size: 24,
    speed: 0.24,
    traits: ["ranged", "armored"],
  },
  hexer: {
    abilities: [
      {
        chance: 1,
        desc: "매혹적인 움직임으로 근처 수비수들을 모두 감속한다",
        duration: 2500,
        intensity: 0.35,
        name: "Hypnotic Dance",
        radius: 80,
        type: "slow",
      },
    ],
    armor: 0.1,
    attackSpeed: 2000,
    bounty: 50,
    category: "ranged",
    color: "#be185d",
    desc: "누구나 볼 때 마비 저주를 짜는 매혹적인 리듬의 움직임을 펼치는 댄스 그룹 오디션 지원자들. 바깥으로 향한 글레이브가 근처 수비수들을 혼미한 상태로 느리게 만드는 최면 패턴을 그린다. 지역마다 늪의 부두술부터 사막의 회전무용, 화산의 불춤까지 다양한 춤 전통을 채택한다.",
    flying: false,
    hp: 350,
    isRanged: true,
    name: "Dance Group Auditions",
    projectileDamage: 60,
    range: 160,
    size: 22,
    speed: 0.28,
    traits: ["ranged"],
  },
  // =============================================================================
  // FLYING ENEMIES (Continued)
  // =============================================================================
  harpy: {
    abilities: [
      {
        chance: 1,
        desc: "날카로운 비명이 수비수들을 어지럽힌다",
        duration: 1500,
        intensity: 0.3,
        name: "비명",
        type: "slow",
      },
    ],
    armor: 0.05,
    bounty: 45,
    category: "flying",
    color: "#7c3aed",
    desc: "날카로운 발톱과 너덜너덜한 날개를 흐릿하게 만들며 방어 사이를 돌파하는 비명을 지르는 공중 포식자들. 관통하는 비명은 타워 조준을 어지럽히고, 대부분의 단일 대상 방어보다 훨씬 빠르게 움직인다. 광역 피해 타워를 쓰거나 손실을 받아들여라 — 하피는 아무도 기다려주지 않는다.",
    flying: true,
    hp: 380,
    name: "Late Meal Rush",
    size: 24,
    speed: 0.6,
    traits: ["flying", "fast", "breakthrough"],
  },
  wyvern: {
    abilities: [
      {
        chance: 0.3,
        desc: "가는 곳마다 모든 것을 불태우는 화염을 내뿜는다",
        duration: 3500,
        intensity: 18,
        name: "화염 숨결",
        radius: 80,
        type: "burn",
      },
    ],
    aoeDamage: 266,
    aoeRadius: 70,
    armor: 0.3,
    attackSpeed: 1800,
    bounty: 110,
    category: "flying",
    color: "#059669",
    desc: "철갑에 가까운 비늘과 돌을 녹일 만큼 뜨거운 숨을 가진 거대한 날개 드레이크. 지상 방어 위로 날아올라 아래 타워에 불을 내리며 한 번 지나갈 때마다 파괴적인 광역 피해를 입힌다. 대공 타워와 장거리 포병만이 안정적으로 이 공중 괴물들을 위협할 수 있다.",
    flying: true,
    hp: 1200,
    isBoss: true,
    isRanged: true,
    liveCost: 3,
    name: "타이거 트랜짓 와이번",
    projectileDamage: 168,
    range: 180,
    size: 36,
    speed: 0.36,
    targetsTroops: true,
    traits: ["flying", "boss", "aoe_attack"],
    troopAttackSpeed: 1800,
    troopDamage: 196,
  },
  specter: {
    abilities: [
      {
        chance: 1,
        desc: "얼리는 오라가 근처 타워의 메커니즘을 감속한다",
        duration: 3000,
        intensity: 0.25,
        name: "Haunting Presence",
        radius: 90,
        type: "tower_slow",
      },
    ],
    armor: 0.3,
    bounty: 80,
    category: "flying",
    color: "#94a3b8",
    desc: "오래전에 죽은 동문의 반투명한 그림자가 고딕 탑 사이의 길을 배회하며, 그 영혼의 냉기가 타워 메커니즘을 기어가게 만든다. 벽을 통과하고 지형 장애물을 무시해 함정에 가둘 수 없다. 빠르게 집중 사격을 하거나 방어선 전체에서 온기를 빼앗기는 꼴을 보라.",
    flying: true,
    hp: 700,
    liveCost: 2,
    name: "파이어스톤 유령",
    size: 26,
    speed: 0.4,
    targetsTroops: true,
    traits: ["flying", "magic_resist", "armored"],
    troopAttackSpeed: 2000,
    troopDamage: 48,
  },
  // =============================================================================
  // CAMPUS ENEMIES - Campus life and events
  // =============================================================================
  berserker: {
    abilities: [
      {
        chance: 0.25,
        desc: "강력한 돌진으로 명중 시 수비수들을 기절시킨다",
        duration: 1200,
        name: "태클",
        type: "stun",
      },
    ],
    armor: 0,
    bounty: 65,
    category: "campus",
    color: "#dc2626",
    desc: "순수한 학술적 분노에 힘입어 돌진하는 미친 전사들, 광전사는 무모한 기세로 방어를 돌파한다. 그들의 파괴적인 돌진은 경로의 모든 것을 기절시키고, 죽음에 가까워질수록 더 빠르고 더 위험해진다. 충격을 여러 방어선에 흡수하도록 분산 배치하라.",
    flying: false,
    hp: 850,
    liveCost: 2,
    name: "캐인 스프리 선수",
    size: 26,
    speed: 0.5,
    traits: ["fast"],
    troopDamage: 72,
  },
  necromancer: {
    abilities: [
      {
        chance: 0.3,
        desc: "짓누르는 실망이 지속 피해를 입힌다",
        duration: 4500,
        intensity: 15,
        name: "Rejection Letter",
        type: "poison",
      },
    ],
    armor: 0.2,
    bounty: 100,
    category: "campus",
    color: "#1e1b4b",
    desc: "쓰러진 학생들의 거부된 논문 초고를 되살려 영혼의 공포를 길로 보내는 금지된 학문의 대가들. 소환된 영혼은 지나가는 모든 것에 지속 피해를 입히고, 사령술사를 죽여도 이미 풀려난 영혼은 멈추지 않는다. 길이 유령으로 채워지기 전에 일찍 제거하라.",
    flying: false,
    hp: 900,
    liveCost: 2,
    name: "입학처장",
    size: 30,
    speed: 0.18,
    summonType: "specter",
    traits: ["summoner", "magic_resist"],
    troopDamage: 88,
  },
  // =============================================================================
  // BOSS ENEMIES - Major threats
  // =============================================================================
  golem: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 10_000,
        desc: "석화시키는 눈빛이 타워를 완전히 무력화한다",
        duration: 4500,
        name: "Stone Gaze",
        radius: 130,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "거대한 진동이 근처 수비수들을 모두 기절시킨다",
        duration: 2500,
        name: "지면 강타",
        radius: 110,
        type: "stun",
      },
    ],
    aoeDamage: 504,
    aoeRadius: 110,
    armor: 0.35,
    bounty: 450,
    category: "campus",
    color: "#57534e",
    desc: "Nassau Hall의 토대 그대로 깎아 만든 이 돌 거인들은 거의 무한한 인내력을 지녔으며 가장 집중된 화력만이 효과적이다. 석화시키는 시선은 타워를 완전히 무력화하고, 지진파 진동은 광범위하게 수비수를 기절시킨다. 가장 강력한 타워를 이 거수에게 쏟아붓지 않으면 그저 방어를 뚫고 지나갈 것이다.",
    flying: false,
    hp: 14_500,
    isBoss: true,
    liveCost: 10,
    name: "나소 사자",
    size: 44,
    speed: 0.09,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    troopDamage: 448,
  },
  shadow_knight: {
    abilities: [
      {
        chance: 1,
        desc: "재정적 영향력이 타워 효과를 약화시킨다",
        duration: 4500,
        intensity: 0.35,
        name: "Endowment Pressure",
        radius: 110,
        type: "tower_weaken",
      },
      {
        chance: 0.2,
        desc: "그림자 불이 수비수들을 태운다",
        duration: 3500,
        intensity: 18,
        name: "Dark Flame",
        type: "burn",
      },
    ],
    armor: 0.5,
    bounty: 120,
    category: "campus",
    color: "#18181b",
    desc: "Princeton의 가장 어두운 전통을 입은 갑옷의 챔피언인 그림자 기사는 신성하지 않은 불꽃에 둘러싸인 채로 비밀 결사의 무한한 자원을 등에 업고 전장을 거닌다. 재정적 영향력은 타워 효과를 약화시키고, 저주받은 그림자 화염은 마법 방어조차도 태워버린다. 즉각적이고 압도적인 화력을 필요로 하는 우선 처리 대상이다.",
    flying: false,
    hp: 1800,
    isBoss: true,
    liveCost: 3,
    name: "Alumni Donor",
    size: 32,
    speed: 0.22,
    traits: ["armored", "boss"],
    troopDamage: 322,
  },
  // =============================================================================
  // CAMPUS ENEMIES (Continued) - Campus life and events
  // =============================================================================
  cultist: {
    abilities: [
      {
        chance: 0.15,
        desc: "피로가 근처 수비수들을 감속한다",
        duration: 2000,
        intensity: 0.2,
        name: "Sleep Deprivation Aura",
        radius: 60,
        type: "slow",
      },
    ],
    armor: 0.05,
    bounty: 22,
    category: "campus",
    color: "#7c2d12",
    desc: "밤샘 공부에 빠진 붉은 눈의 광신도들이 금지된 학술 의식을 외시하며 기진맥진한 황홀경으로 앞으로 비틀거린다. 피로의 오라는 근처 모든 것을 감속시키고, 종종 서로의 약화 효과를 증폭시키는 무리로 나타난다. 개별적으로는 싸이게 잡지만 숫자가 되면 압도적이다.",
    flying: false,
    hp: 320,
    name: "Finals Week Cultist",
    size: 21,
    speed: 0.4,
    traits: [],
    troopDamage: 27,
  },
  plaguebearer: {
    abilities: [
      {
        chance: 0.35,
        desc: "주변 수비수들에게 전염시킨다",
        duration: 5500,
        intensity: 10,
        name: "전염",
        radius: 80,
        type: "poison",
      },
      {
        chance: 0.25,
        desc: "질병으로 수비수들을 약화시킨다",
        duration: 3500,
        intensity: 0.3,
        name: "열",
        type: "slow",
      },
    ],
    armor: 0.15,
    bounty: 40,
    category: "campus",
    color: "#65a30d",
    desc: "학술적 절망의 뒤틀린 담체로서 지나간 자리에 전염되는 비참함을 남긴다. 지나가는 길 근처의 모든 타워와 수비수는 효과를 줄이는 전염병에 걸리고 시간이 지나며 중독된다. 방어들을 넓게 분포시켜라 — 역병 매개체에 몰려 있는 것은 사형 선고다.",
    flying: false,
    hp: 520,
    liveCost: 2,
    name: "Flu Season Carrier",
    size: 25,
    speed: 0.25,
    traits: ["aoe_attack"],
    troopDamage: 58,
  },
  frostling: {
    abilities: [
      {
        chance: 1,
        desc: "얼리는 공격으로 수비수를 감속한다",
        duration: 2000,
        intensity: 0.35,
        name: "Frost Touch",
        type: "slow",
      },
    ],
    armor: 0.1,
    bounty: 35,
    breakthrough: true,
    category: "campus",
    color: "#7dd3fc",
    desc: "1월의 텅 빈 캠퍼스의 혹독한 추위에서 태어난 서리 정령은 순수한 겨울의 냉기를 가진 반투명 영혼이며 모든 물리 장벽을 통과한다. 동상의 손길은 수비수를 느리게 만들고 눈이 덮인 지형에선 거의 보이지도 않는다. 빠르고, 잘 빠져나가며, 추적하기가 미치도록 답답하다.",
    flying: false,
    hp: 350,
    name: "방학 귀신",
    size: 22,
    speed: 0.45,
    traits: ["fast", "breakthrough"],
  },
  infernal: {
    abilities: [
      {
        chance: 0.35,
        desc: "근처 모두에게 과로의 불을 퍼뜨린다",
        duration: 4000,
        intensity: 25,
        name: "소진 화염",
        radius: 85,
        type: "burn",
      },
      {
        chance: 1,
        desc: "근처 타워의 효과가 줄어든다",
        duration: 3500,
        intensity: 0.25,
        name: "Exhaustion Aura",
        radius: 100,
        type: "tower_weaken",
      },
    ],
    armor: 0.25,
    bounty: 85,
    category: "campus",
    color: "#dc2626",
    desc: "학술적 번아웃과 불가능한 마감에 타오르는 현현, 지옥불은 근처 타워를 오작동하고 수비수에게 지속 화염 피해를 입힐 만큼 격렬한 열을 발산한다. 과로의 오라는 다른 지옥불과 중첩되어 무리로 모이면 기하급수적으로 위험해진다. 가장 강력한 단일 대상 타워로 빠르게 처리하라.",
    flying: false,
    hp: 1100,
    liveCost: 2,
    name: "소진 악마",
    size: 30,
    speed: 0.28,
    traits: ["aoe_attack"],
    troopDamage: 95,
  },
  assassin: {
    abilities: [
      {
        chance: 0.4,
        desc: "학술적 과성취의 독",
        duration: 3000,
        intensity: 15,
        name: "Toxic Excellence",
        type: "poison",
      },
    ],
    armor: 0,
    bounty: 45,
    breakthrough: true,
    category: "campus",
    color: "#1e1b4b",
    desc: "조용하고 눈부시게 빠른 암살자는 타워가 목표를 잡기도 전에 방어선을 가로질러 질주한다. 독이 발린 칼날은 스치기만 해도 지속 피해를 남기고, 그 속도는 느리게 발사하는 무기로는 거의 막을 수 없다. 경로 위로 빠른 공격 타워를 겹쳐 쌓거나 빠져나가는 것을 받아들여라.",
    flying: false,
    hp: 320,
    liveCost: 2,
    name: "Curve Wrecker",
    size: 20,
    speed: 0.7,
    traits: ["fast", "breakthrough"],
    troopDamage: 36,
  },
  // =============================================================================
  // NATURE ENEMIES - Environmental/biome creatures
  // =============================================================================
  thornwalker: {
    abilities: [
      {
        chance: 0.35,
        desc: "독성 가시가 접촉 시 중독을 입힌다",
        duration: 4000,
        intensity: 10,
        name: "Thorn Poison",
        type: "poison",
      },
    ],
    armor: 0.35,
    bounty: 55,
    category: "forest",
    color: "#166534",
    desc: "한때 아름다웠던 Princeton 인동이 어둠의 마법에 의해 독성 가시의 걷는 덤불로 타락했다. 지속적으로 체력을 회복하며, 근거리에서 공격하는 타워는 독성 가시에 피해를 입는다. 지속 원거리 화력이 유일한 안정적인 대응이다 — 근접 방어는 가시보행자 앞에서 시들어버릴 것이다.",
    flying: false,
    hp: 680,
    name: "Ivy Overgrowth",
    size: 28,
    speed: 0.2,
    traits: ["armored", "regenerating"],
  },
  // =============================================================================
  // BOSS ENEMIES (Continued) - Major threats
  // =============================================================================
  sandworm: {
    abilities: [
      {
        chance: 0.25,
        desc: "지면에서 튀어나오며 근처 모두를 기절시킨다",
        duration: 1800,
        name: "Emergence",
        radius: 110,
        type: "stun",
      },
    ],
    aoeDamage: 378,
    aoeRadius: 100,
    armor: 0.4,
    bounty: 95,
    category: "desert",
    color: "#a16207",
    desc: "전장 아래로 터널을 파는 거대한 공포들, 예고 없이 튀어나와 타워와 수비수를 모두 집어삼킨다. 출현은 광범위한 반경을 기절시키고 지상으로 방어선 구간을 우회할 수도 있다. 특징적인 진동에 주의를 기울이고 광역 거부 준비를 하라.",
    flying: false,
    hp: 1600,
    isBoss: true,
    liveCost: 4,
    name: "Thesis Devourer",
    size: 38,
    speed: 0.16,
    traits: ["armored", "boss", "aoe_attack"],
    troopDamage: 180,
  },
  juggernaut: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 12_000,
        desc: "압도적인 위세가 타워를 완전히 shut down한다",
        duration: 4000,
        name: "Tenure Review",
        radius: 110,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "압도적인 힘이 모든 수비수를 기절시킨다",
        duration: 2000,
        name: "Authority Slam",
        radius: 100,
        type: "stun",
      },
    ],
    aoeDamage: 420,
    aoeRadius: 95,
    armor: 0.6,
    bounty: 200,
    category: "campus",
    color: "#44403c",
    desc: "수십억 달러의 기금으로 뒷받침되는 제도적 권력의 멈출 수 없는 거수. 정복자의 압도적 위세는 주변 타워를 완전히 shut down하고, 지진파 돌진은 전체 방어선을 기절시킨다. 이 위협을 무시할 수 없다 — 가진 것을 다 쏟아붓지 않으면 방어가 무너지는 것을 보게 될 것이다.",
    flying: false,
    hp: 4200,
    isBoss: true,
    liveCost: 6,
    name: "Endowed Chair",
    size: 40,
    speed: 0.1,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    troopDamage: 240,
  },
  // =============================================================================
  // FLYING ENEMIES (Continued) - Aerial threats
  // =============================================================================
  banshee: {
    abilities: [
      {
        chance: 0.25,
        desc: "관통하는 비명이 근처 모든 수비수를 기절시킨다",
        duration: 1000,
        name: "절망의 통곡",
        radius: 70,
        type: "stun",
      },
      {
        chance: 1,
        desc: "애도하는 울음소리가 타워 조준을 방해한다",
        duration: 2500,
        intensity: 0.3,
        name: "Haunting Cry",
        radius: 80,
        type: "tower_slow",
      },
    ],
    armor: 0.45,
    bounty: 50,
    category: "flying",
    color: "#e2e8f0",
    desc: "최종 성적표를 본 학생들의 고통 받는 영혼들, 뱅시는 밤마다 울부짖으며 광범위한 반경에서 수비수를 기절시키고 타워 조준을 방해한다. 끔찍할 정도로 빠르고 장애물을 통과해 가장 다루기 어려운 적 중 하나다. 광역 기절 저항이 필수다.",
    flying: true,
    hp: 480,
    liveCost: 2,
    name: "Grade Wailing Spirit",
    size: 24,
    speed: 0.55,
    targetsTroops: true,
    traits: ["flying", "fast", "magic_resist"],
    troopAttackSpeed: 1500,
    troopDamage: 55,
  },
  dragon: {
    abilities: [
      {
        chance: 0.35,
        desc: "세대를 관통하는 태우는 불꽃",
        duration: 5000,
        intensity: 25,
        name: "Legacy Flame",
        radius: 100,
        type: "burn",
      },
      {
        chance: 0.15,
        cooldown: 15_000,
        desc: "지원을 철회해 타워를 완전히 무력화한다",
        duration: 4000,
        name: "Endowment Freeze",
        radius: 150,
        type: "tower_disable",
      },
      {
        chance: 0.2,
        desc: "귀를 먹먹하게 하는 포효가 근처 모두를 기절시킨다",
        duration: 2500,
        name: "Roar of Ages",
        radius: 120,
        type: "stun",
      },
    ],
    aoeDamage: 616,
    aoeRadius: 120,
    armor: 0.38,
    attackSpeed: 2200,
    bounty: 500,
    category: "flying",
    color: "#9f1239",
    desc: "Princeton 창립 시대의 신화적 후원자, 재단이 파괴적인 화염 숨결을 연료로 하는 불을 뿜는 용으로 환생했다. 그 존재만으로도 수백 년 전통의 무게로 타워를 무력화하고, 천지를 진동시키는 포효는 근처의 모든 수비수를 기절시킨다. 학술 동물 도감의 정점 포식자 — 그에 맞춰 준비하라.",
    flying: true,
    hp: 12_000,
    isBoss: true,
    isRanged: true,
    liveCost: 10,
    name: "고대 동문",
    projectileDamage: 420,
    range: 240,
    size: 48,
    speed: 0.12,
    targetsTroops: true,
    traits: ["flying", "boss", "aoe_attack", "tower_debuffer"],
    troopAttackSpeed: 2200,
    troopDamage: 336,
  },
  // =============================================================================
  // SWARM ENEMIES - Fast, weak, numerous
  // =============================================================================
  athlete: {
    armor: 0,
    bounty: 10,
    breakthrough: true,
    category: "campus",
    color: "#f97316",
    desc: "올림픽급의 속도와 민첩성으로 방어선을 가로지르는 대학 운동부 선수들, 평범한 적을 멈출 장애물도 뛰어넘는다. 싸우기 위해 멈추지 않는다 — 그저 경로의 모든 것을 뛰어넘는다. 가장 빠르게 발사하는 타워만이 사라지기 전에 명중시킬 수 있는 희망을 가진다.",
    flying: false,
    hp: 210,
    name: "대학 러너",
    size: 20,
    speed: 0.58,
    traits: ["fast", "breakthrough"],
    troopDamage: 10,
  },
  // =============================================================================
  // CAMPUS ENEMIES (Regional) - Campus life
  // =============================================================================
  tiger_fan: {
    abilities: [
      {
        chance: 0.15,
        desc: "귀를 먹먹하게 하는 환호가 수비수 집중력을 흔든다",
        duration: 1500,
        intensity: 0.2,
        name: "호랑이들아 앞으로!",
        radius: 50,
        type: "slow",
      },
    ],
    armor: 0.15,
    bounty: 12,
    category: "campus",
    color: "#ef4444",
    desc: "거품 손가락과 약한 공격을 튕겨내는 환호 깃발로 갑옷을 입은 시끄러운 Princeton 수퍼팬들. 귀를 먹먹하게 하는 환호가 수비수 집중력을 흔들고 근처 적의 사기를 높인다. 개별적으로는 관리할만하지만, 팀워크 오라는 주변 위협을 상당히 더 위험하게 만든다.",
    flying: false,
    hp: 230,
    name: "호랑이 팬",
    size: 22,
    speed: 0.34,
    traits: ["armored"],
    troopDamage: 25,
  },
  // =============================================================================
  // NATURE ENEMIES - Swamp Region
  // =============================================================================
  bog_creature: {
    abilities: [
      {
        chance: 0.25,
        desc: "독성 점액이 접촉 시 중독시킨다",
        duration: 3000,
        intensity: 6,
        name: "Toxic Muck",
        type: "poison",
      },
    ],
    armor: 0.2,
    bounty: 14,
    category: "swamp",
    color: "#365314",
    desc: "늪물의 곪는 깊숙한 곳에서 건져 올린 비틀거리는 공포들, 몸은 근처 모든 것을 중독시키는 독성 진흙의 층으로 뒤덮여 있다. 고통스러울 정도로 느리지만 불안할 정도로 질기며, 부식성 점액은 거대한 양의 고통을 흡수하면서 타워 기초를 갉아먹는다. 방어 근처에서 머물게 하지 마라.",
    flying: false,
    hp: 220,
    name: "늪 잠복자",
    size: 24,
    speed: 0.28,
    traits: ["armored"],
    troopDamage: 20,
  },
  will_o_wisp: {
    abilities: [
      {
        chance: 1,
        desc: "현혹하는 빛이 타워 사거리를 줄인다",
        duration: 2500,
        intensity: 0.15,
        name: "Mesmerizing Light",
        radius: 60,
        type: "tower_blind",
      },
    ],
    armor: 0.4,
    bounty: 10,
    category: "swamp",
    color: "#84cc16",
    desc: "벽과 방어가 없는 것처럼 미끄러지듯 통과하는 적대적인 늪빛의 깜빡이는 오브들. 최면의 빛이 타워 조준 사거리를 줄이고, 그들의 영적 본성은 물리 피해에 면역이 된다. 마법 타워만이 이 영혼 유인등을 안정적으로 해칠 수 있다.",
    flying: true,
    hp: 90,
    name: "도깨비불",
    size: 18,
    speed: 0.5,
    traits: ["flying", "fast", "magic_resist", "breakthrough"],
    troopDamage: 16,
  },
  swamp_troll: {
    abilities: [
      {
        chance: 0.2,
        desc: "강한 주먹이 수비수를 기절시킨다",
        duration: 1200,
        name: "곤봉 강타",
        type: "stun",
      },
    ],
    armor: 0.25,
    bounty: 25,
    category: "swamp",
    color: "#4d7c0f",
    desc: "기생성 자라나물로 장식되고 불쾌한 늪물이 뚝뚝 떨어지는 거대한 늪의 무인. 피부의 수분에서 끊임없이 체력을 회복하고, 거대한 주먹은 천둥 같은 일격마다 수비수를 기절시킨다. 빠르게 폭발시켜 처리하라 — 재생 능력이 화력보다 오래 살아남을 수 있다.",
    flying: false,
    hp: 450,
    liveCost: 2,
    name: "늪 트롤",
    size: 30,
    speed: 0.2,
    traits: ["armored", "regenerating"],
    troopDamage: 55,
  },
  // =============================================================================
  // NATURE ENEMIES - Desert Region
  // =============================================================================
  nomad: {
    abilities: [
      {
        chance: 0.2,
        desc: "눈을 멀게 하는 모래를 일으켜 근처 수비수를 감속한다",
        duration: 2500,
        intensity: 0.25,
        name: "Sandstorm Shroud",
        type: "slow" as const,
      },
    ],
    armor: 0.1,
    bounty: 11,
    category: "desert",
    color: "#a16207",
    desc: "고대 어둠의 계약에 묶인 저주받은 사막 유랑자들, 유랑자는 지나가면서 타워 시야와 사거리를 줄이는 눈 먼 모래 폭풍을 일으킨다. 햇볕에 단련된 몸은 보이는 것보다 질기고 잊혀진 문명의 속삭임을 지니고 있다. 가혹한 풍경을 횡단하는 것에 맞춰 의상과 무기를 바꾼다.",
    flying: false,
    hp: 160,
    name: "Desert Nomad",
    size: 22,
    speed: 0.38,
    traits: ["fast"],
    troopDamage: 17,
  },
  scorpion: {
    abilities: [
      {
        chance: 0.35,
        desc: "독성 침이 대상을 중독시킨다",
        duration: 4000,
        intensity: 12,
        name: "독 쏘임",
        type: "poison",
      },
    ],
    armor: 0.3,
    bounty: 18,
    category: "desert",
    color: "#78350f",
    desc: "성의 갑옷보다 두꺼운 키틴질 갑옷으로 둘러싸인 거대한 사막 거미류. 독성 침은 초기 타격 이후에도 오래 지속되는 마비 독을 주입하고, 집게는 타워 기초를 으스러뜨린다. 장갑 관통 공격이 필수다 — 일반 무기는 그 흑요석 등껍질을 거의 흠집도 내지 못한다.",
    flying: false,
    hp: 280,
    name: "Giant Scorpion",
    size: 26,
    speed: 0.32,
    traits: ["armored"],
    troopDamage: 42,
  },
  scarab: {
    armor: 0.15,
    bounty: 9,
    breakthrough: true,
    category: "desert",
    color: "#fbbf24",
    desc: "모래 위를 눈부시게 빠른 속도로 종종거리는 마법의 풍뎅이, 황금빛 등껍질은 보호용 상형 문양으로 빛난다. 대부분의 타워가 효과적으로 조준하기엔 너무 빠르고 너무 작아, 모래처럼 손가락 사이로 빠져나간다. 광역 공격만이 안정적인 답이다.",
    flying: false,
    hp: 140,
    name: "Sacred Scarab",
    size: 16,
    speed: 0.45,
    traits: ["fast", "breakthrough"],
    troopDamage: 18,
  },
  // =============================================================================
  // NATURE ENEMIES - Winter Region
  // =============================================================================
  snow_goblin: {
    abilities: [
      {
        chance: 1,
        desc: "얼리는 발톱이 대상을 감속한다",
        duration: 1500,
        intensity: 0.25,
        name: "Frost Claws",
        type: "slow",
      },
    ],
    armor: 0.05,
    bounty: 9,
    breakthrough: true,
    category: "winter",
    color: "#93c5fd",
    desc: "얼음 위를 질주하는 키득거리는 서리 정령, 그들의 얼리는 발톱은 긁히는 수비수라면 누구든 감속시킨다. 작고 빠르며 짜증나게 잘 빠져, 대부분의 조준 시스템이 잠그기도 전에 타워 사이를 누빈다. 종종 혼돈의 숫자로 방어를 압도하는 떼로 나타난다.",
    flying: false,
    hp: 130,
    name: "Frost Goblin",
    size: 20,
    speed: 0.48,
    traits: ["fast", "breakthrough"],
    troopDamage: 18,
  },
  yeti: {
    abilities: [
      {
        chance: 0.25,
        desc: "강력한 얼음 내리치기가 근처 수비수를 기절시킨다",
        duration: 1800,
        name: "Frost Slam",
        radius: 75,
        type: "stun",
      },
      {
        chance: 1,
        desc: "냉기 오라가 근처 모두를 감속한다",
        duration: 2500,
        intensity: 0.35,
        name: "Chilling Presence",
        radius: 70,
        type: "slow",
      },
    ],
    aoeDamage: 85,
    aoeRadius: 70,
    armor: 0.35,
    bounty: 30,
    category: "winter",
    color: "#e0f2fe",
    desc: "걷는 빙하처럼 전장을 뒤덮는 거대한 모피 덮인 몸집의 태초의 얼음 거인들. 천둥 같은 얼음 내리치기는 근처의 모든 것을 기절시키는 충격파를 보내고, 얼리는 오라는 범위 내 모든 타워 메커니즘을 감속시킨다. 게임에서 가장 무서운 탱크 중 하나 — 즉시 중화력을 쏟아라.",
    flying: false,
    hp: 520,
    liveCost: 2,
    name: "Mountain Yeti",
    size: 32,
    speed: 0.18,
    traits: ["armored", "aoe_attack"],
    troopDamage: 62,
  },
  ice_witch: {
    abilities: [
      {
        chance: 1,
        desc: "얼리는 투사체가 대상을 크게 감속한다",
        duration: 2500,
        intensity: 0.4,
        name: "Ice Bolt",
        type: "slow",
      },
      {
        chance: 1,
        desc: "오싹한 마법이 타워 메커니즘을 감속한다",
        duration: 3000,
        intensity: 0.25,
        name: "Winter's Grasp",
        radius: 80,
        type: "tower_slow",
      },
    ],
    armor: 0.2,
    attackSpeed: 2000,
    bounty: 20,
    category: "winter",
    color: "#60a5fa",
    desc: "겨울 자체를 무기로 쓰는 고대 빙화술사, 결정질 투사체를 발사해 대상을 꽁꽁 얼리고 그 존재만으로 타워 메커니즘을 시려게 한다. 겨울 지역에서는 폭풍이 그들의 힘을 증폭시켜 서리 마법이 강해진다. 여러 빠른 공격 타워를 그들에게 조준해 두어라 — 얼어있는 타워 하나가 너무 많다.",
    flying: false,
    hp: 200,
    isRanged: true,
    name: "Frost Sorceress",
    projectileDamage: 40,
    range: 200,
    size: 24,
    speed: 0.3,
    traits: ["ranged", "magic_resist"],
  },
  // =============================================================================
  // NATURE ENEMIES - Volcanic Region
  // =============================================================================
  magma_spawn: {
    abilities: [
      {
        chance: 0.35,
        desc: "마그마 접촉 시 화상을 입힌다",
        duration: 3000,
        intensity: 12,
        name: "Molten Touch",
        type: "burn",
      },
    ],
    armor: 0.25,
    bounty: 16,
    category: "volcanic",
    color: "#ea580c",
    desc: "화산 분화구에서 태어나는 용해 원소, 지나가는 모든 걸 그 발걸음마다 그을린다. 마그마 형태와의 접촉은 수비수에게 지속적으로 화상을 입히고, 지나간 자리에 용암 웅덩이를 남긴다. 거리에서 맞을 수 있다면 의외로 약하다 — 가까이 오게 하지 마라.",
    flying: false,
    hp: 250,
    name: "마그마 산물",
    size: 24,
    speed: 0.26,
    traits: ["armored"],
  },
  fire_imp: {
    abilities: [
      {
        chance: 0.25,
        desc: "작지만 아픈 불꽃",
        duration: 2000,
        intensity: 8,
        name: "Imp Fire",
        type: "burn",
      },
    ],
    armor: 0,
    bounty: 8,
    breakthrough: true,
    category: "volcanic",
    color: "#fb923c",
    desc: "깜빡이는 지옥불에 둘러싸인 즐거워하는 작은 악마들, 불 임프는 주황색 불꽃의 줄무늬로 방어를 가로질러 질주한다. 작고 기민해 느린 발사체를 짜증나게 쉽게 피하며, 불길의 꼬리가 수비수에게 피해를 입힌다. 개별적으로는 성가시지만, 그들이 선호하는 떼로 이동하면 치명적이다.",
    flying: false,
    hp: 110,
    name: "화염 임프",
    size: 18,
    speed: 0.52,
    traits: ["fast", "breakthrough"],
    troopDamage: 18,
  },
  ember_guard: {
    abilities: [
      {
        chance: 0.3,
        desc: "불타는 무기가 화상 상처를 입힌다",
        duration: 3500,
        intensity: 15,
        name: "Ember Blade",
        type: "burn",
      },
      {
        chance: 1,
        desc: "강렬한 열이 타워 정확도를 방해한다",
        duration: 2500,
        intensity: 0.15,
        name: "Heat Shimmer",
        radius: 70,
        type: "tower_weaken",
      },
    ],
    armor: 0.35,
    bounty: 22,
    category: "volcanic",
    color: "#c2410c",
    desc: "사실상 화산 불에 단련된 흑요석 판금 갑옷의 정예 지옥 기사. 불타는 무기는 지속 피해를 주는 화상 상처를 입히고, 갑옷에서 발산되는 강렬한 열은 타워 정확도를 방해한다. 가장 질긴 보스가 아닌 적 중 하나 — 화산 강철은 가장 강력한 공격만 튕겨낸다.",
    flying: false,
    hp: 380,
    name: "잿불 경비",
    size: 28,
    speed: 0.25,
    traits: ["armored"],
  },
  // =============================================================================
  // BUG ENEMIES - Grassland Region
  // =============================================================================
  orb_weaver: {
    abilities: [
      {
        chance: 0.25,
        cooldown: 8000,
        desc: "수비수를 끈적한 거미줄로 감싸 움직이지 못하게 한다",
        duration: 3000,
        name: "Silk Cocoon",
        type: "stun",
      },
      {
        chance: 1,
        desc: "거미줄을 남겨 타워 공격 속도를 감속한다",
        duration: 4000,
        intensity: 0.3,
        name: "거미줄 함정",
        radius: 60,
        type: "tower_slow",
      },
    ],
    armor: 0.15,
    bounty: 20,
    category: "insectoid",
    color: "#4a3728",
    desc: "전장에 마비 거미줄을 짜는 거대한 거미, 개별 수비수를 고치처럼 감싸고 근처 모든 것을 느리게 만드는 끈적한 가닥으로 영역을 덮는다. 여덟 개의 눈이 동시에 여러 대상을 추적해 측면 공격이 불가능하다. 화염 기반 타워로 거미줄을 태우지 않으면 방어선이 멈춘다.",
    flying: false,
    hp: 320,
    name: "Orb Weaver Spider",
    nativeRegion: "grassland",
    size: 28,
    speed: 0.28,
    traits: ["tower_debuffer"],
    troopDamage: 38,
  },
  mantis: {
    abilities: [
      {
        chance: 0.3,
        desc: "번개 일격이 대상을 순간적으로 기절시킨다",
        duration: 1500,
        name: "매복 강타",
        type: "stun",
      },
    ],
    armor: 0.1,
    bounty: 16,
    category: "insectoid",
    color: "#65a30d",
    desc: "낫 같은 앞다리로 단 한 번의 공격에 타워를 두 동강 낼 수 있는 번개처럼 빠른 매복 포식자들. 먹이가 사거리 안에 들어올 때까지 미동 없이 기다리다가 어떤 조준 시스템도 반응하기 전에 치명적인 행동으로 폭발한다. 일격의 기절은 보복 전 사라질 시간을 준다 — 광역 거부가 유일한 안정적 대응이다.",
    flying: false,
    hp: 240,
    name: "Praying Mantis",
    nativeRegion: "grassland",
    size: 24,
    speed: 0.42,
    traits: ["fast"],
    troopDamage: 55,
  },
  bombardier_beetle: {
    abilities: [
      {
        chance: 0.4,
        desc: "과열된 화학 용액이 대상을 태운다",
        duration: 3000,
        intensity: 10,
        name: "산성 분사",
        radius: 50,
        type: "burn",
      },
    ],
    armor: 0.35,
    attackSpeed: 2500,
    bounty: 17,
    category: "insectoid",
    color: "#1e3a5f",
    desc: "강화된 키틴질로 둘러싸인 공성급 곤충, 폭격 풍뎅이는 타워 갑옷과 수비수 방패를 모두 태우는 과열 화학 용액을 발사한다. 폭발성 산선은 지상 벌레에게서는 보기 드문 파괴적 원거리 능력을 부여한다. 일찍 조준하라 — 포격 위치에 자리 잡으면 피해가 끊임없다.",
    flying: false,
    hp: 260,
    isRanged: true,
    name: "폭격수 딱정벌레",
    nativeRegion: "grassland",
    projectileDamage: 30,
    range: 140,
    size: 22,
    speed: 0.3,
    traits: ["armored", "ranged"],
  },
  // =============================================================================
  // BUG ENEMIES - Swamp Region
  // =============================================================================
  mosquito: {
    abilities: [
      {
        chance: 0.35,
        desc: "피를 빼앗아 대상을 중독시키고 자신을 치유한다",
        duration: 3000,
        intensity: 8,
        name: "피 흡수",
        type: "poison",
      },
    ],
    armor: 0,
    bounty: 10,
    category: "insectoid",
    color: "#6b2142",
    desc: "우스꽝스러울 정도로 부풀어 오른 흡혈귀로 수비수에 붙어 생명력을 빼앗고 기생적인 물림마다 자신을 치유한다. 먹을수록 더 크고 질겨진다. 중독 효과가 중첩되어 잠깐의 접촉도 위험하다. 죽일 수 없는 괴물로 부풀어 오르기 전에 빠르게 잡아라.",
    flying: true,
    hp: 150,
    name: "Giant Mosquito",
    nativeRegion: "swamp",
    size: 20,
    speed: 0.5,
    traits: ["flying", "fast"],
    troopDamage: 20,
  },
  centipede: {
    abilities: [
      {
        chance: 0.4,
        desc: "다리 공격마다 마비 독을 주입한다",
        duration: 4000,
        intensity: 14,
        name: "지네 독",
        type: "poison",
      },
      {
        chance: 0.2,
        desc: "대상 주위를 감싸 속도를 줄인다",
        duration: 2500,
        intensity: 0.35,
        name: "Coiling Grip",
        type: "slow",
      },
    ],
    armor: 0.4,
    bounty: 22,
    category: "insectoid",
    color: "#7c2d12",
    desc: "수많은 다리마다 마비 독을 주입하는 갑옷의 다분절 악몽. 분절된 몸은 대상을 감싸 속도를 줄이고, 분절을 파괴해도 죽지 않는다 — 그저 남은 몸이 더 화나고 더 빨라질 뿐이다. 어떻게 접근하든 길고 가혹한 전투다.",
    flying: false,
    hp: 400,
    name: "Marsh Centipede",
    nativeRegion: "swamp",
    size: 30,
    speed: 0.24,
    traits: ["armored"],
    troopDamage: 45,
  },
  dragonfly: {
    armor: 0,
    bounty: 8,
    breakthrough: true,
    category: "insectoid",
    color: "#0ea5e9",
    desc: "어떤 타워도 안정적으로 추적하기엔 너무 빠른 속도로 하늘을 누비는 무지개빛 공중 포식자들. 보석 톤의 날개는 조준 시스템을 혼란시키는 현혹 패턴으로 빛을 굴절시킨다. 순수한 속도 위협 — 대공이 빠른 움직임을 잡지 못하면 이들이 도전을 받지 않고 곧바로 통과한다.",
    flying: true,
    hp: 120,
    name: "Swamp Dragonfly",
    nativeRegion: "swamp",
    size: 18,
    speed: 0.6,
    traits: ["flying", "fast", "breakthrough"],
    troopDamage: 15,
  },
  silk_moth: {
    abilities: [
      {
        chance: 1,
        desc: "반짝이는 비늘을 흩뿌려 타워 사거리를 줄인다",
        duration: 3500,
        intensity: 0.3,
        name: "실명 비늘",
        radius: 80,
        type: "tower_blind",
      },
    ],
    armor: 0.05,
    bounty: 14,
    category: "insectoid",
    color: "#c4b5fd",
    desc: "반짝이는 날개 비늘이 무지갯빛 먼지 구름으로 흩어져 타워 조준 시스템을 멀게 하는 ethereal 나방들. 조용히 방어를 지나가는 것처럼 표류하며 지나가는 모든 타워의 사거리를 줄인다. 위험하게도 — 단 한 마리의 비단나방이 방어 통로 전체의 정확성을 무력화할 수 있다.",
    flying: true,
    hp: 200,
    name: "Phantom Moth",
    nativeRegion: "swamp",
    size: 22,
    speed: 0.35,
    traits: ["flying", "tower_debuffer"],
  },
  // =============================================================================
  // BUG ENEMIES - Desert Region
  // =============================================================================
  ant_soldier: {
    abilities: [
      {
        chance: 0.2,
        desc: "강력한 턱이 수비수를 으스러뜨리고 기절시킨다",
        duration: 1800,
        name: "Mandible Crush",
        type: "stun",
      },
    ],
    armor: 0.25,
    bounty: 20,
    category: "insectoid",
    color: "#92400e",
    desc: "광대한 지하 식민지의 단정한 전사들, 개미 군인은 명중 시 기절시키는 으스러뜨리는 턱으로 같은 보행 대형으로 행진한다. 숨겨진 터널 네트워크에서 증원을 소환해, 한 마리를 죽이는 것이 종종 세 마리 더 오는 것을 촉발한다. 영역 피해로 터널을 압도하는 것이 흐름을 막는 유일한 방법이다.",
    flying: false,
    hp: 350,
    name: "Sand Ant Soldier",
    nativeRegion: "desert",
    size: 24,
    speed: 0.3,
    summonCount: 2,
    summonType: "scarab",
    traits: ["armored", "summoner"],
    troopDamage: 40,
  },
  locust: {
    armor: 0,
    bounty: 7,
    breakthrough: true,
    category: "insectoid",
    color: "#a3a323",
    desc: "경로의 모든 유기체를 집어삼키는 탐욕스러운 떼 지능의 개별 세포. 단독으로는 약하지만 최대치의 광역 타워조차 압도하는 종말론적 숫자로 도착한다. 떼가 적응한다 — 한 지점에서 충분히 죽이면 나머지는 가장 약한 틈새로 우회한다.",
    flying: true,
    hp: 100,
    name: "Desert Locust",
    nativeRegion: "desert",
    size: 16,
    speed: 0.55,
    traits: ["flying", "fast", "breakthrough"],
    troopDamage: 12,
  },
  trapdoor_spider: {
    abilities: [
      {
        chance: 0.3,
        cooldown: 7000,
        desc: "은신에서 뛰어나와 대상을 고치로 감싼다",
        duration: 2500,
        name: "매복 고치",
        type: "stun",
      },
      {
        chance: 0.1,
        cooldown: 12_000,
        desc: "타워 아래를 파고 들어가 잠시 무력화한다",
        duration: 2000,
        name: "굴 파고 들기",
        type: "tower_disable",
      },
    ],
    armor: 0.3,
    bounty: 18,
    category: "insectoid",
    color: "#78350f",
    desc: "타워 기초 아래로 파고든 다음 위로 폭발해 피해자를 끊어지지 않는 비단으로 감싸는 인내심 많은 매복 포식자들. 가장 취약한 위치를 공격하기 위해 방어 아래를 파고들며, 파묻힌 상태에서는 타워에 완전히 보이지 않는다. 알려진 거미 경로를 따라 탐지 능력을 배치하거나 예고 없이 타워를 잃거나 둘 중 하나다.",
    flying: false,
    hp: 280,
    name: "Trapdoor Spider",
    nativeRegion: "desert",
    size: 26,
    speed: 0.26,
    traits: ["armored"],
    troopDamage: 50,
  },
  // =============================================================================
  // BUG ENEMIES - Winter Region
  // =============================================================================
  ice_beetle: {
    abilities: [
      {
        chance: 1,
        desc: "극심한 추위가 근처 모든 타워 메커니즘을 감속한다",
        duration: 3000,
        intensity: 0.35,
        name: "서리 오라",
        radius: 90,
        type: "tower_slow",
      },
      {
        chance: 0.3,
        desc: "얼리는 턱이 수비수를 감속한다",
        duration: 2000,
        intensity: 0.3,
        name: "Icy Bite",
        type: "slow",
      },
    ],
    armor: 0.4,
    bounty: 20,
    category: "insectoid",
    color: "#67e8f9",
    desc: "초자연적 추위를 발산하는 결정성 얼음 갑옷으로 둘러싸인 풍뎅이, 광범위한 오라에서 타워 메커니즘을 얼리고 수비수를 감속시킨다. 턱은 얼리는 물림을 전달해 대상을 제자리에 고정하고, 반사 등껍질은 들어오는 투사체의 일부를 튕겨낸다. 겨울 자신의 곤충 형태의 공성 병기다.",
    flying: false,
    hp: 340,
    name: "Frost Beetle",
    nativeRegion: "winter",
    size: 24,
    speed: 0.25,
    traits: ["armored", "tower_debuffer"],
    troopDamage: 35,
  },
  frost_tick: {
    abilities: [
      {
        chance: 1,
        desc: "타워에 붙어 에너지를 빼앗는다",
        duration: 4000,
        intensity: 0.3,
        name: "Power Drain",
        radius: 60,
        type: "tower_weaken",
      },
    ],
    armor: 0.1,
    bounty: 12,
    category: "insectoid",
    color: "#a5f3fc",
    desc: "얼음 턱으로 타워 기초에 붙어 에너지를 빼앗는 기생성 서리 거미, 제거될 때까지 출력을 줄인다. 대부분의 직접 사격 타워를 피할 만큼 작고 광역 피해를 견딜 만큼 질기다. 타워를 정기적으로 점검하라 — 서리 진드기 감염이 방어 네트워크 전체를 조용히 무력화할 수 있다.",
    flying: false,
    hp: 180,
    name: "Frost Tick",
    nativeRegion: "winter",
    size: 18,
    speed: 0.38,
    traits: ["tower_debuffer"],
    troopDamage: 25,
  },
  snow_moth: {
    abilities: [
      {
        chance: 1,
        desc: "서리 먼지 구름이 타워 조준 사거리를 줄인다",
        duration: 3000,
        intensity: 0.35,
        name: "백색 폭풍 날개",
        radius: 70,
        type: "tower_blind",
      },
    ],
    armor: 0,
    bounty: 11,
    category: "insectoid",
    color: "#e0f2fe",
    desc: "서리 가득한 날개가 만드는 국지적 눈보라로 타워 조준 사거리를 거의 0으로 줄이는 영혼 겨울 나방들. 만든 화이트아웃 안에서 조용히 표류하며 대부분의 탐지에 보이지 않는다. 겨울 지역에서는 눈보라 효과가 전체 방어 구역을 멀게 하는 완전한 화이트아웃으로 강해진다.",
    flying: true,
    hp: 160,
    name: "Snow Moth",
    nativeRegion: "winter",
    size: 20,
    speed: 0.4,
    traits: ["flying", "tower_debuffer"],
  },
  // =============================================================================
  // BUG ENEMIES - Volcanic Region
  // =============================================================================
  fire_ant: {
    abilities: [
      {
        chance: 0.3,
        desc: "근처 수비수에게 타는 듯한 분비물을 뱉는다",
        duration: 3500,
        intensity: 12,
        name: "Magma Spit",
        radius: 50,
        type: "burn",
      },
    ],
    armor: 0.3,
    bounty: 28,
    category: "insectoid",
    color: "#dc2626",
    desc: "화산 개미 식민지의 타오르는 모태, 과열된 brood chamber에서 끊임없이 불타는 군인 개미를 생성한다. 근처 수비수에게 작열하는 분비물을 뱉는 동안 아이들이 모든 방향에서 떼로 몰려든다. 여왕을 빠르게 죽이지 않으면 결코 멈추지 않는 불의 증원 파도에 빠져 죽는다.",
    flying: false,
    hp: 450,
    name: "Fire Ant Queen",
    nativeRegion: "volcanic",
    size: 30,
    speed: 0.22,
    summonCount: 2,
    summonType: "fire_imp",
    traits: ["armored", "summoner"],
    troopDamage: 48,
  },
  magma_beetle: {
    abilities: [
      {
        chance: 0.4,
        desc: "과열된 등껍질이 접촉 시 공격자를 태운다",
        duration: 3000,
        intensity: 14,
        name: "Molten Shell",
        type: "burn",
      },
      {
        chance: 1,
        desc: "강렬한 열이 타워 메커니즘을 뒤틀게 한다",
        duration: 2500,
        intensity: 0.2,
        name: "Heat Warp",
        radius: 60,
        type: "tower_weaken",
      },
    ],
    armor: 0.45,
    bounty: 24,
    category: "insectoid",
    color: "#b91c1c",
    desc: "흑요석 판금으로 둘러싸인 살아있는 용광로, 마그마 풍뎅이는 근접 공격자가 접촉 시 타오를 만큼 격렬한 열을 발산한다. 용해된 피가 등껍질이 깨질 때 분사돼 근처 수비수에게 광역 피해를 입힌다. 과열된 등껍질이 타워 메커니즘을 뒤틀어 범위에 머무는 동안 정확도를 줄인다.",
    flying: false,
    hp: 380,
    name: "Magma Beetle",
    nativeRegion: "volcanic",
    size: 26,
    speed: 0.22,
    traits: ["armored"],
    troopDamage: 42,
  },
  ash_moth: {
    abilities: [
      {
        chance: 0.35,
        desc: "타는 불씨를 흩뿌려 수비수에 불을 붙인다",
        duration: 2500,
        intensity: 10,
        name: "Ember Trail",
        radius: 40,
        type: "burn",
      },
    ],
    armor: 0.05,
    bounty: 12,
    category: "insectoid",
    color: "#f97316",
    desc: "화산 재 구름에서 태어나, 이 그을은 비나방은 날갯짓마다 타는 불씨를 전장에 흩뿌린다. 남긴 불씨 자국은 수비수에 불을 붙이고 비나방이 지나간 후에도 오래 남는다. 화산 지역에서는 주변 열이 불씨 출력을 연속 불폭풍으로 과충전한다.",
    flying: true,
    hp: 170,
    name: "Cinder Moth",
    nativeRegion: "volcanic",
    size: 20,
    speed: 0.45,
    traits: ["flying"],
  },
  // =============================================================================
  // BUG BOSS
  // =============================================================================
  brood_mother: {
    abilities: [
      {
        chance: 0.2,
        cooldown: 12_000,
        desc: "광범위한 호로 비단을 뿌려 여러 수비수를 고치로 감싼다",
        duration: 3500,
        name: "Mass Cocoon",
        radius: 100,
        type: "stun",
      },
      {
        chance: 0.15,
        cooldown: 15_000,
        desc: "타워를 두꺼운 거미줄로 완전히 감싼다",
        duration: 4000,
        name: "거미줄 장막",
        radius: 80,
        type: "tower_disable",
      },
      {
        chance: 0.3,
        desc: "치명적인 독이 근처 모든 수비수를 약화시킨다",
        duration: 5000,
        intensity: 18,
        name: "군락 독",
        radius: 80,
        type: "poison",
      },
    ],
    aoeDamage: 336,
    aoeRadius: 90,
    armor: 0.4,
    bounty: 300,
    category: "insectoid",
    color: "#1c1917",
    desc: "끔찍할 정도로 거대한 고대 거미 여왕, 복부는 끊임없이 독성 거미 새끼의 물결을 낳는다. 광범위한 비단 스프레이는 동시에 여러 수비수를 고치로 감싸고, 끊어지지 않는 거미줄은 타워를 완전히 감쌀 수 있다. 존재하는 가장 치명적인 절지동물 — 방어가 비단과 산유물로 뒤덮이기 전에 가능한 모든 화력을 집중하라.",
    flying: false,
    hp: 6000,
    isBoss: true,
    liveCost: 8,
    name: "군락 모체",
    nativeRegion: "grassland",
    size: 42,
    speed: 0.12,
    summonCount: 3,
    summonType: "orb_weaver",
    traits: ["armored", "boss", "summoner", "aoe_attack", "tower_debuffer"],
    troopDamage: 280,
  },
  // =============================================================================
  // FANTASY CREATURES - Grassland Region
  // =============================================================================
  dire_bear: {
    abilities: [
      {
        chance: 0.25,
        cooldown: 8000,
        desc: "거대한 발 휘두르기가 근처 모든 수비수를 기절시킨다",
        duration: 2000,
        name: "Thunderous Swipe",
        radius: 70,
        type: "stun",
      },
    ],
    aoeDamage: 60,
    aoeRadius: 70,
    armor: 0.35,
    bounty: 35,
    category: "forest",
    color: "#5c3a1e",
    desc: "가장 무거운 공격만 튕겨내는 철갑 같은 가죽의 거대한 곰 포식자. 천둥 같은 발 내리치기는 근처의 모든 것을 기절시키는 충격파를 보내고, 광전사적 분노는 피해를 입을수록 강해진다. 가장 직관적이면서도 파괴적인 자연 보스 중 하나 — 속임수 없는 순수한 힘의 화신.",
    flying: false,
    hp: 650,
    name: "Dire Bear",
    size: 32,
    speed: 0.2,
    traits: ["armored", "aoe_attack"],
    troopDamage: 75,
  },
  ancient_ent: {
    abilities: [
      {
        chance: 0.2,
        cooldown: 10_000,
        desc: "뿌리가 지면에서 튀어나와 수비수를 움직이지 못하게 한다",
        duration: 3000,
        name: "Root Entangle",
        radius: 80,
        type: "stun",
      },
      {
        chance: 1,
        desc: "덩굴이 타워 메커니즘으로 파고든다",
        duration: 4000,
        intensity: 0.25,
        name: "Overgrowth",
        radius: 70,
        type: "tower_slow",
      },
    ],
    aoeDamage: 50,
    aoeRadius: 80,
    armor: 0.3,
    bounty: 45,
    category: "forest",
    color: "#2d5016",
    desc: "고대 살아있는 나무의 걷는 요새, 거대한 뿌리는 타워와 수비수를 엉켜 묶으려고 땅에서 튀어나온다. 껍질로 덮인 몸은 어떤 상처에서든 회복되며, 기어가는 덩굴은 효과를 줄이기 위해 타워 메커니즘으로 침투한다. 소모전의 화신 — 지속 폭발 피해가 끊임없는 치유를 극복할 수 있는 유일한 방법이다.",
    flying: false,
    hp: 900,
    name: "고대 엔트",
    size: 36,
    speed: 0.12,
    traits: ["armored", "regenerating", "aoe_attack"],
    troopDamage: 60,
  },
  forest_troll: {
    abilities: [
      {
        chance: 0.2,
        desc: "거대한 통나무 곤봉을 휘두른다",
        duration: 1500,
        name: "곤봉 강타",
        type: "stun",
      },
    ],
    armor: 0.2,
    bounty: 25,
    category: "forest",
    color: "#4a6741",
    desc: "거의 모든 상처에서 회복되며 잘린 팔다리를 몇 초 안에 다시 키우는 깊은 숲의 우락부락한 거한들. 거대한 통나무 곤봉은 수비수를 흩어버리는 기절 일격을 주고, 회복할 때마다 더 화나고 더 공격적으로 돌아온다. 화염 기반 타워가 강력히 권장된다 — 그것이 효과를 내는 유일한 피해 유형이다.",
    flying: false,
    hp: 480,
    name: "Forest Troll",
    size: 28,
    speed: 0.26,
    traits: ["armored", "regenerating"],
    troopDamage: 55,
  },
  timber_wolf: {
    abilities: [
      {
        chance: 0.3,
        desc: "다리를 물어 대상을 감속한다",
        duration: 2000,
        intensity: 0.25,
        name: "Hamstring",
        type: "slow",
      },
    ],
    armor: 0.05,
    bounty: 10,
    breakthrough: true,
    category: "forest",
    color: "#6b6b6b",
    desc: "측면을 공격하고 타워가 반응하기 전 틈새를 빠져나가는 무서운 지능으로 공격을 조율하는 번개처럼 빠른 무리 사냥꾼들. 얼리는 물림은 조금이라도 깨무는 수비수라면 누구든 감속시키고, 항상 여러 각도에서 공격하는 무리로 이동한다. 속도와 숫자는 그들이 나타나는 모든 물결에서 지속적 위협이 된다.",
    flying: false,
    hp: 160,
    name: "Timber Wolf",
    size: 20,
    speed: 0.55,
    traits: ["fast", "breakthrough"],
    troopDamage: 28,
  },
  giant_eagle: {
    abilities: [
      {
        chance: 0.25,
        desc: "고속 다이브가 명중 시 대상을 기절시킨다",
        duration: 1200,
        name: "Diving Strike",
        type: "stun",
      },
    ],
    armor: 0.05,
    bounty: 16,
    category: "forest",
    color: "#c8a050",
    desc: "전장 위를 선회할 때 태양을 가리는 거대한 날개폭을 가진 위엄 있는 랩터. 파괴적인 다이브 공격은 명중 시 대상을 기절시키고 강철 같은 발톱은 타워 외장을 찢는다. 가장 빠른 대공 방어만이 고공 스윕과 예측 불가능한 공격 패턴을 통해 그것들을 추적할 수 있다.",
    flying: true,
    hp: 220,
    name: "Giant Eagle",
    size: 34,
    speed: 0.48,
    traits: ["flying", "fast"],
    troopDamage: 35,
  },
  // =============================================================================
  // FANTASY CREATURES - Swamp Region
  // =============================================================================
  swamp_hydra: {
    abilities: [
      {
        chance: 0.35,
        desc: "여러 머리가 동시에 독을 뿜는다",
        duration: 4000,
        intensity: 14,
        name: "Multi-Head Venom",
        radius: 70,
        type: "poison",
      },
    ],
    aoeDamage: 55,
    aoeRadius: 90,
    armor: 0.25,
    bounty: 50,
    category: "swamp",
    color: "#2e4a2e",
    desc: "독립적으로 조준하는 각 머리에서 부식성 독을 뿜는 꿈틀대는 다중 머리 뱀류 악몽. 한 머리를 잘라도 두 개가 다시 자라나며 각각 마지막보다 더 공격적이다. 머리 수가 통제 불능으로 곤두박질치기 전에 지속적이고 집중된 피해로 몸 자체를 죽이는 것이 유일한 안정적인 전략이다.",
    flying: false,
    hp: 800,
    name: "Swamp Hydra",
    size: 34,
    speed: 0.15,
    traits: ["armored", "regenerating", "aoe_attack"],
    troopDamage: 70,
  },
  giant_toad: {
    abilities: [
      {
        chance: 0.3,
        desc: "피부에서 마비성 독소를 분비한다",
        duration: 3000,
        intensity: 10,
        name: "Toxic Secretion",
        type: "poison",
      },
      {
        chance: 0.2,
        cooldown: 6000,
        desc: "채찍 같은 혀로 멀리서 수비수를 낚아채 명중 시 기절시킨다",
        duration: 1500,
        name: "Tongue Lash",
        type: "stun",
      },
    ],
    armor: 0.15,
    bounty: 18,
    category: "swamp",
    color: "#5a7a3a",
    desc: "채찍 같은 혀로 전장 건너편에서 수비수를 낚아채 명중 시 기절시키는 기괴한 양서류. 피부는 근처 모든 것을 마비시키는 환각성 독소를 분비하고, 부풀어 오른 몸은 놀라울 만큼의 피해를 흡수한다. 우스꽝스러운 외관에 비해 위험하게도 — 늪 두꺼비를 절대 과소평가하지 마라.",
    flying: false,
    hp: 300,
    name: "Giant Toad",
    size: 26,
    speed: 0.28,
    traits: [],
    troopDamage: 40,
  },
  vine_serpent: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 12_000,
        desc: "타워를 감싸 완전히 무력화한다",
        duration: 3000,
        name: "수축",
        radius: 50,
        type: "tower_disable",
      },
      {
        chance: 0.3,
        desc: "가시 덩굴이 닿는 것을 모두 감속한다",
        duration: 2500,
        intensity: 0.3,
        name: "Thorned Grasp",
        type: "slow",
      },
    ],
    armor: 0.1,
    bounty: 16,
    category: "swamp",
    color: "#3a6b3a",
    desc: "어두운 늪 마법에 의해 살아 움직이는 가시 덩굴의 꿈틀거리는 무더기, 덩굴 뱀은 타워를 감싸 완전히 무력화하고 그 가시는 근처 모든 것을 감속한다. 조이는 힘은 시간이 지날수록 강해져 갇힌 구조물에 점점 더 많은 피해를 입힌다. 도달 범위 밖에 배치된 원거리 타워가 가장 안전한 대응이다.",
    flying: false,
    hp: 250,
    name: "덩굴 뱀",
    size: 22,
    speed: 0.32,
    traits: ["tower_debuffer"],
    troopDamage: 30,
  },
  marsh_troll: {
    abilities: [
      {
        chance: 0.3,
        desc: "공격이 수비수에 중독을 입히는 감염을 남긴다",
        duration: 3500,
        intensity: 10,
        name: "악취 강타",
        type: "poison",
      },
    ],
    armor: 0.2,
    bounty: 24,
    category: "swamp",
    color: "#4a5a3a",
    desc: "축축한 진흙 코팅이 상처를 독성 늪 진흙으로 봉인해 끊임없는 회복을 부여하는 늪에 사는 거한들. 감염된 발톱은 근처 수비수에게 질병을 퍼뜨리는 독성 상처를 남긴다. 모든 트롤처럼, 화염 피해는 회복을 우회한다 — 없이는 그저 던지는 모든 것을 무시할 뿐이다.",
    flying: false,
    hp: 440,
    name: "Marsh Troll",
    size: 28,
    speed: 0.24,
    traits: ["armored", "regenerating"],
    troopDamage: 50,
  },
  // =============================================================================
  // FANTASY CREATURES - Desert Region
  // =============================================================================
  phoenix: {
    abilities: [
      {
        chance: 1,
        desc: "성스러운 불이 근처 모든 수비수를 태운다",
        duration: 3000,
        intensity: 15,
        name: "Immolation Aura",
        radius: 60,
        type: "burn",
      },
    ],
    armor: 0.1,
    bounty: 40,
    category: "desert",
    color: "#ff6600",
    desc: "비행 경로의 모든 것을 그을리는 성스러운 불꽃에 둘러싸인 불사조. 파괴될 때 자신의 재에서 환생해 완전히 치유되고 격노한 채 피닉스 불꽃의 눈부신 폭발로 폭발한다. 두 번 죽여야 한다 — 한 번은 물리적 형체를 산산조각내고, 다시 한 번은 그 안에 있는 영원히 꺼지지 않는 불씨를 끄기 위해.",
    flying: true,
    hp: 500,
    name: "불사조",
    size: 28,
    speed: 0.35,
    traits: ["flying", "regenerating"],
    troopDamage: 45,
  },
  basilisk: {
    abilities: [
      {
        chance: 0.2,
        cooldown: 10_000,
        desc: "수비수를 순간적으로 돌로 만든다",
        duration: 3000,
        name: "Petrifying Gaze",
        radius: 60,
        type: "stun",
      },
      {
        chance: 0.1,
        cooldown: 15_000,
        desc: "타워의 메커니즘을 단단하게 석화시킨다",
        duration: 2500,
        name: "Stone Stare",
        type: "tower_disable",
      },
    ],
    armor: 0.4,
    bounty: 35,
    category: "desert",
    color: "#6b6b3a",
    desc: "대부분의 일반 공격을 튕겨내는 돌처럼 단단한 비늘로 뒤덮인 고대 뱀. 석화시키는 시선은 수비수를 돌로 만들고 타워 메커니즘을 단단히 얼려 집결된 방어에서 연쇄적 장애를 일으킨다. 멀리서 접근하고 눈을 마주치지 마라 — 직접 교전은 사형 선고다.",
    flying: false,
    hp: 550,
    name: "바실리스크",
    size: 30,
    speed: 0.18,
    traits: ["armored"],
    troopDamage: 55,
  },
  djinn: {
    abilities: [
      {
        chance: 1,
        desc: "눈을 멀게 하는 모래를 일으켜 타워 사거리를 줄인다",
        duration: 4000,
        intensity: 0.35,
        name: "모래폭풍",
        radius: 100,
        type: "tower_blind",
      },
    ],
    armor: 0.15,
    attackSpeed: 2200,
    bounty: 28,
    category: "desert",
    color: "#6a3aaa",
    desc: "전체 방어 구역을 멀게 할 수 있는 격렬한 모래 폭풍을 명령하는 사막 바람의 태초의 영혼들. 그들의 ethereal한 몸은 물리 장벽을 통과하고 바람 마법은 발사 중인 투사체를 흩뜨린다. 마법 피해와 광역 거부 타워만이 이 고대 불가해한 존재를 안정적으로 해칠 수 있다.",
    flying: false,
    hp: 350,
    isRanged: true,
    name: "모래 진",
    projectileDamage: 35,
    range: 160,
    size: 26,
    speed: 0.34,
    traits: ["ranged", "magic_resist", "tower_debuffer"],
  },
  manticore: {
    abilities: [
      {
        chance: 0.35,
        desc: "독 묻은 꼬리 가시를 발사한다",
        duration: 3500,
        intensity: 12,
        name: "Tail Barbs",
        type: "poison",
      },
    ],
    armor: 0.2,
    attackSpeed: 1800,
    bounty: 30,
    category: "desert",
    color: "#8b4513",
    desc: "거대한 사자의 근육질 몸체, 광대한 박쥐 같은 날개, 독성 가시의 화살비를 발사하는 분절된 전갈 꼬리를 가진 무시무시한 키메라. 격렬한 feline 머리는 호박색 눈과 갑옷 판금을 으스러뜨릴 수 있는 검 같은 송곳니를 가졌다. 파괴적인 근접 능력을 치명적 원거리 독을 결합 — 동물 도감에서 가장 다양한 위협 중 하나.",
    flying: true,
    hp: 420,
    isRanged: true,
    name: "만티코어",
    projectileDamage: 28,
    range: 150,
    size: 28,
    speed: 0.3,
    traits: ["flying", "ranged", "armored"],
    troopDamage: 45,
  },
  // =============================================================================
  // FANTASY CREATURES - Winter Region
  // =============================================================================
  frost_troll: {
    abilities: [
      {
        chance: 1,
        desc: "극심한 추위가 근처 모든 타워 메커니즘을 감속한다",
        duration: 3500,
        intensity: 0.3,
        name: "서리 오라",
        radius: 80,
        type: "tower_slow",
      },
      {
        chance: 0.25,
        desc: "얼음으로 덮인 주먹이 접촉 시 수비수를 얼린다",
        duration: 2500,
        intensity: 0.35,
        name: "Freezing Slam",
        type: "slow",
      },
    ],
    armor: 0.25,
    bounty: 28,
    category: "winter",
    color: "#5a8aaa",
    desc: "초자연적 추위를 발산하는 껍질 얼음 갑옷으로 둘러싸인 거대한 재생 거한. 타워는 그 존재만으로도 꽁꽁 얼고 얼음 주먹은 수비수를 제자리에 고정시키는 얼리는 일격을 전달한다. 모든 트롤처럼 끊임없이 회복하지만 화염 피해는 얼음 껍질을 녹여 회복을 막는다.",
    flying: false,
    hp: 520,
    name: "Frost Troll",
    size: 30,
    speed: 0.22,
    traits: ["armored", "regenerating", "tower_debuffer"],
    troopDamage: 55,
  },
  dire_wolf: {
    abilities: [
      {
        chance: 0.3,
        desc: "얼리는 물림이 수비수를 감속한다",
        duration: 2000,
        intensity: 0.25,
        name: "Frost Bite",
        type: "slow",
      },
    ],
    armor: 0.15,
    bounty: 12,
    category: "winter",
    color: "#4a4a5a",
    desc: "서리로 덮인 모피와 빙하의 갈망으로 빛나는 눈을 가진 거대한 알파 포식자. 근처 방어를 측면에서 공포의 속도로 두리번거리며 얼리는 물림은 닿는 모든 것을 감속시킨다. 너무 빨라서 도망칠 수도 없고 너무 질겨서 무시할 수도 없으며 너무 똑똑해서 함정에 가둘 수도 없다 — 얼어붙은 황무지의 정점 무리 사냥꾼.",
    flying: false,
    hp: 600,
    name: "공포늑대",
    size: 22,
    speed: 0.52,
    traits: ["fast", "armored"],
    troopDamage: 35,
  },
  wendigo: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 12_000,
        desc: "소름 돋는 비명이 공포로 타워를 무력화한다",
        duration: 2500,
        name: "Terror Shriek",
        radius: 70,
        type: "tower_disable",
      },
      {
        chance: 0.2,
        desc: "야만적인 발톱이 수비수를 기절시킨다",
        duration: 1500,
        name: "Rending Claws",
        type: "stun",
      },
    ],
    armor: 0.15,
    bounty: 25,
    category: "winter",
    color: "#3a3a4a",
    desc: "끝없는 겨울의 기근과 광기에서 태어난 야위고 사슴 뿔이 달린 공포들. 피가 끓어오르는 비명은 원초적이고 뼛속까지의 공포로 수비수를 마비시키고 야만적인 발톱은 잡는 것을 무엇이든 기절시킨다. 쓰러진 수비수를 잡아먹으며 강하고 빨라진다 — 잡아먹지 못하거나 점점 격화되는 악몽을 상대하거나 둘 중 하나다.",
    flying: false,
    hp: 780,
    name: "웬디고",
    size: 26,
    speed: 0.4,
    traits: ["fast", "tower_debuffer"],
    troopDamage: 60,
  },
  mammoth: {
    abilities: [
      {
        chance: 0.2,
        cooldown: 8000,
        desc: "천둥 같은 발걸음이 근처 모든 수비수를 기절시킨다",
        duration: 2500,
        name: "지진 발구르기",
        radius: 120,
        type: "stun",
      },
      {
        chance: 1,
        desc: "지반 진동이 타워 정확도를 방해한다",
        duration: 3000,
        intensity: 0.25,
        name: "Tremor",
        radius: 110,
        type: "tower_weaken",
      },
    ],
    aoeDamage: 120,
    aoeRadius: 130,
    armor: 0.55,
    attackSpeed: 2800,
    bounty: 150,
    category: "winter",
    color: "#8b7355",
    desc: "활을 쏘는 궁수로 가득한 하우다를 등에 짊어진 거대한 갑옷 전쟁 짐승, 매머드 자체가 방어를 돌진한다. 철로 덮인 어금니와 지진파 발걸음은 경로의 모든 것을 기절시키고 흩어버리며 두꺼운 가죽은 대부분의 투사체를 튕겨낸다. 조각조각 분해해야 하는 이동형 요새다.",
    flying: false,
    hp: 10_000,
    isRanged: true,
    liveCost: 6,
    name: "전쟁 매머드",
    projectileDamage: 65,
    range: 200,
    size: 52,
    speed: 0.11,
    traits: ["armored", "aoe_attack", "ranged"],
    troopDamage: 150,
  },
  // =============================================================================
  // FANTASY CREATURES - Volcanic Region
  // =============================================================================
  lava_golem: {
    abilities: [
      {
        chance: 1,
        desc: "근처 모두를 태우는 강렬한 열을 발산한다",
        duration: 3000,
        intensity: 16,
        name: "Molten Aura",
        radius: 70,
        type: "burn",
      },
      {
        chance: 1,
        desc: "극심한 열이 타워 메커니즘을 뒤틀게 한다",
        duration: 3000,
        intensity: 0.25,
        name: "열 왜곡",
        radius: 80,
        type: "tower_weaken",
      },
    ],
    armor: 0.5,
    bounty: 40,
    category: "volcanic",
    color: "#8b2500",
    desc: "용해된 암석과 화산 흑요석의 살아있는 산이 멀리서도 타워 메커니즘을 뒤틀 만큼 강한 열을 발산한다. 과열된 몸은 닿는 모든 것을 태우며, 거의 파괴할 수 없는 돌 껍질은 지속적이고 무거운 화력으로 간신히 깨어진다. 궁극의 화산 탱크 — 보통 적보다는 움직이는 환경 위험으로 취급하라.",
    flying: false,
    hp: 700,
    name: "Lava Golem",
    size: 34,
    speed: 0.16,
    traits: ["armored"],
    troopDamage: 65,
  },
  volcanic_drake: {
    abilities: [
      {
        chance: 0.35,
        desc: "용불꽃의 원뿔을 내뿜는다",
        duration: 3500,
        intensity: 14,
        name: "화염 숨결",
        radius: 60,
        type: "burn",
      },
    ],
    armor: 0.2,
    bounty: 32,
    category: "volcanic",
    color: "#cc3300",
    desc: "화산 분화구에서 태어난 무시무시한 드레이크, 거대한 악마의 뿔과 흑요석 갑옷 두개골은 정점 화산 포식자로 표시한다. 열로 일렁이는 날개로 방어 위로 날아올라 아래의 모든 것을 불태우는 용불꽃 원뿜을 내뿜는다. 두껍게 갑옷 입은 몸과 파괴적 숨 무기는 게임에서 가장 위험한 공중 위협 중 하나다.",
    flying: true,
    hp: 450,
    name: "화산 드레이크",
    size: 28,
    speed: 0.32,
    traits: ["flying", "armored"],
    troopDamage: 50,
  },
  salamander: {
    abilities: [
      {
        chance: 0.4,
        desc: "수비수를 그을리는 타는 발자국을 남긴다",
        duration: 2500,
        intensity: 10,
        name: "Flame Trail",
        type: "burn",
      },
    ],
    armor: 0.15,
    bounty: 18,
    category: "volcanic",
    color: "#ff4500",
    desc: "거대한 갑옷 두개골과 타오르는 파충류 눈을 가진 끔찍한 원소 도마뱀은 모든 불 출처에서 체력을 회복한다. 수비수를 그을리는 타는 발자국 자국을 남기고 등쪽 불꽃 능선이 열을 흡수할수록 강해진다. 화산 지역에서는 거의 죽일 수 없다 — 얼음이나 물리 피해로 불 흡수를 우회하라.",
    flying: false,
    hp: 280,
    name: "Fire Salamander",
    size: 22,
    speed: 0.42,
    traits: ["fast", "regenerating"],
    troopDamage: 35,
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Skeletons
  // =============================================================================
  skeleton_footman: {
    armor: 0,
    bounty: 10,
    category: "dark_fantasy",
    color: "#d4c5a0",
    desc: "잊혀진 식사 클럽 멤버의 딸깍거리는 부활된 뼈, 해골 보병은 덜걱거리며 파도처럼 돌진한다. 빠르지만 부서지기 쉽고 집중된 화력 아래 부서진다 — 그러나 속도와 숫자 덕분에 항상 일부가 빠져나간다. Nassau의 언데 데 군대의 대포 fodder, expendable하고 끊임없이 대체 가능하다.",
    flying: false,
    hp: 180,
    name: "Prospect Street Bones",
    size: 20,
    speed: 0.48,
    traits: ["fast"],
    troopDamage: 14,
  },
  skeleton_knight: {
    abilities: [
      {
        chance: 0.2,
        desc: "녹슨 방패로 수비수를 후려친다",
        duration: 1200,
        name: "Shield Bash",
        type: "stun",
      },
    ],
    armor: 0.35,
    bounty: 40,
    category: "dark_fantasy",
    color: "#8b8068",
    desc: "녹슬었지만 여전히 기능하는 갑옷이 오래전에 해산된 식사 클럽의 문장을 여전히 달고 있는 고대 전사들. 녹슨 방패는 빗나가는 공격을 튕겨내고, 단정한 대형은 부서지기 쉬운 골격이 암시하는 것보다 훨씬 위험하다. 죽음에서도 전통이 Princeton에서 무시무시한 힘을 가진다는 것을 상기시킨다.",
    flying: false,
    hp: 550,
    name: "Old Guard Skeleton",
    size: 26,
    speed: 0.28,
    traits: ["armored"],
    troopDamage: 52,
  },
  skeleton_archer: {
    abilities: [
      {
        chance: 0.25,
        desc: "화살이 독성 뼈 파편으로 부서진다",
        duration: 3000,
        intensity: 8,
        name: "뼈 조각",
        type: "poison",
      },
    ],
    armor: 0.05,
    attackSpeed: 2000,
    bounty: 28,
    category: "dark_fantasy",
    color: "#c4b590",
    desc: "고딕 아치에 앉아 극단적 거리에서 놀라운 정확도로 뼈 파편 화살을 퍼붓는 해골 저격수. 독성 뼈 투사체는 명중 시 부서져 근처 수비수에게 독성 파편을 퍼뜨린다. 자리가 잡히기 전에 죽여라 — once 자리 잡으면 정밀 사격이 타워 하나씩 방어를 분해할 수 있다.",
    flying: false,
    hp: 260,
    isRanged: true,
    name: "블레어 아치 궁수",
    projectileDamage: 38,
    range: 200,
    size: 22,
    speed: 0.32,
    traits: ["ranged"],
  },
  skeleton_king: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 10_000,
        desc: "군주의 권위가 타워를 완전히 shut down한다",
        duration: 3500,
        name: "왕의 칙령",
        radius: 120,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "왕권을 휘두르며 근처 모든 수비수를 기절시킨다",
        duration: 2000,
        name: "뼈 왕좌 강타",
        radius: 100,
        type: "stun",
      },
    ],
    aoeDamage: 392,
    aoeRadius: 100,
    armor: 0.45,
    bounty: 250,
    category: "dark_fantasy",
    color: "#daa520",
    desc: "Nassau Hall 아래 묘실의 왕관을 쓴 군주, 고대 권쇠의 한 번 흔들림으로 언데 데 군대를 지휘한다. 군주의 권위는 타워를 완전히 shut down하고 권쇠 내리치기는 근처 모든 수비수를 기절시키는 충격파를 보낸다. 죽으면 군대 전체가 먼지가 되도록 만드는 우선 처리 대상이다.",
    flying: false,
    hp: 5500,
    isBoss: true,
    liveCost: 6,
    name: "나소 홀 대군주",
    size: 38,
    speed: 0.14,
    summonCount: 3,
    summonType: "skeleton_footman",
    traits: ["armored", "boss", "summoner", "aoe_attack"],
    troopDamage: 364,
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Zombies
  // =============================================================================
  zombie_shambler: {
    abilities: [
      {
        chance: 0.2,
        desc: "전염되는 게으름이 수비수를 감속한다",
        duration: 2000,
        intensity: 0.15,
        name: "Contagious Lethargy",
        type: "slow",
      },
    ],
    armor: 0,
    bounty: 8,
    category: "dark_fantasy",
    color: "#5a7247",
    desc: "8시 강의에 가는 월요일 아침 학생들의 죽은 눈의 결의로 비틀거리며 앞으로 가는 신음하는 부활된 시체들. 고통스러울 정도로 느리지만 완전히 끊임없고, 전염되는 게으름 오라는 근처 모든 수비수를 감속시킨다. 인내심과 타워 인내력을 시험하는 거대한 파도로 도착한다.",
    flying: false,
    hp: 250,
    name: "Monday 8AM Shambler",
    size: 21,
    speed: 0.2,
    traits: [],
    troopDamage: 18,
  },
  zombie_brute: {
    abilities: [
      {
        chance: 0.2,
        desc: "엄청난 힘으로 수비수를 잡고 기절시킨다",
        duration: 1500,
        name: "Crushing Grip",
        type: "stun",
      },
      {
        chance: 0.3,
        desc: "부패하는 살이 근처 수비수를 중독시킨다",
        duration: 4000,
        intensity: 10,
        name: "Rotting Aura",
        radius: 70,
        type: "poison",
      },
    ],
    aoeDamage: 80,
    aoeRadius: 70,
    armor: 0.4,
    bounty: 70,
    category: "dark_fantasy",
    color: "#4a5d3a",
    desc: "녹슨 사슬에 감싸이고 괴사 근육으로 부풀어 오른 부풀어 오른 언데 데 괴물. 엄청난 양의 고통을 흡수하고, 엄청난 힘으로 수비수를 잡고 기절시키며, 부패하는 살은 근처 모든 것을 중독시킨다. 좀비 떼의 중보병 — 모든 타격이 젖은 콘크리트를 치는 것 같다.",
    flying: false,
    hp: 1200,
    liveCost: 2,
    name: "Midterm Mauler",
    size: 32,
    speed: 0.15,
    traits: ["armored", "aoe_attack"],
    troopDamage: 90,
  },
  zombie_spitter: {
    abilities: [
      {
        chance: 0.35,
        desc: "부식성 구토가 대상을 중독시키고 약화시킨다",
        duration: 3500,
        intensity: 12,
        name: "산성 담즙",
        type: "poison",
      },
    ],
    armor: 0.1,
    attackSpeed: 2400,
    bounty: 30,
    category: "dark_fantasy",
    color: "#7cb342",
    desc: "식당의 부패된 노동자의 부활, 그 타락한 위장은 생물학적 무기가 되어 대상을 멀리서 중독시키고 약화시키는 부식성 담즙의 흐름을 발사한다. 독성 구토는 지면에 남아 수비수에 지속 피해를 주는 위험 구역을 만든다. 오염을 최소화하기 위해 타워를 분산 배치하라.",
    flying: false,
    hp: 340,
    isRanged: true,
    name: "식당 망자",
    projectileDamage: 55,
    range: 180,
    size: 24,
    speed: 0.22,
    traits: ["ranged"],
  },
  ghoul: {
    abilities: [
      {
        chance: 0.2,
        desc: "소름 돋는 비명이 근처 수비수를 짧게 감속한다",
        duration: 1500,
        intensity: 0.25,
        name: "Paralyzing Shriek",
        radius: 50,
        type: "slow",
      },
    ],
    armor: 0,
    bounty: 18,
    breakthrough: true,
    category: "dark_fantasy",
    color: "#6b5b73",
    desc: "영원한 수면 부족으로 완전히 미쳐버린 야생 언데 데, 굴렁이는 것은 피가 끓어오르는 비명을 지르며 근처 모든 타워를 짧게 감속시킨다. 예측 불가능한 광기 어린 이동 패턴은 추적하기 어렵고 종종 여러 차선을 가로질러 흩어지는 무리로 도착한다. 빠른 발사 타워가 봉쇄에 필수다.",
    flying: false,
    hp: 280,
    name: "All-Nighter Ghoul",
    size: 20,
    speed: 0.55,
    traits: ["fast", "breakthrough"],
    troopDamage: 22,
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Dark Knights
  // =============================================================================
  dark_knight: {
    abilities: [
      {
        chance: 0.25,
        desc: "파괴적인 검격이 수비수를 기절시킨다",
        duration: 1500,
        name: "Dark Cleave",
        type: "stun",
      },
      {
        chance: 1,
        desc: "공포의 오라가 근처 타워를 약화시킨다",
        duration: 3000,
        intensity: 0.2,
        name: "Dread Presence",
        radius: 80,
        type: "tower_weaken",
      },
    ],
    armor: 0.5,
    bounty: 100,
    category: "dark_fantasy",
    color: "#2d2d3d",
    desc: "각 발걸음이 아래의 땅을 갈라놓을 만큼 무거운 흑요석 판금 갑옷에 둘러싸인 흉포한 전사들. 파괴적인 검격은 수비수를 기절시키고 초자연적 공포의 오라는 범위 내 모든 타워를 약화시킨다. 정예 언데 데 중보병 — 느린 접근을 과소평가하지 마라.",
    flying: false,
    hp: 1500,
    liveCost: 2,
    name: "캐논 그린 챔피언",
    size: 30,
    speed: 0.22,
    traits: ["armored"],
    troopDamage: 105,
  },
  death_knight: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 10_000,
        desc: "타워 에너지를 완전히 빼앗는다",
        duration: 4000,
        name: "Soul Reap",
        radius: 120,
        type: "tower_disable",
      },
      {
        chance: 0.3,
        desc: "저주받은 불이 수비수를 안에서부터 태운다",
        duration: 4000,
        intensity: 20,
        name: "사악한 불꽃",
        radius: 90,
        type: "burn",
      },
      {
        chance: 0.2,
        desc: "거대한 충격파가 근처 모두를 기절시킨다",
        duration: 2200,
        name: "Dread Slam",
        radius: 110,
        type: "stun",
      },
    ],
    aoeDamage: 448,
    aoeRadius: 100,
    armor: 0.55,
    bounty: 300,
    category: "dark_fantasy",
    color: "#1a1a2e",
    desc: "FitzRandolph Gate의 언데 데 챔피언, 죽음 기사는 쓰러진 수비수의 영혼을 잡아먹는 저주받은 칼을 휘두른다. 어둠의 마법은 타워 에너지를 완전히 빼앗고, 저주받은 불은 안에서부터 태우며, 거대한 충격파 공격은 근처 모든 것을 기절시킨다. 단독으로 방어선을 분해할 수 있는 다중 위협 악몽.",
    flying: false,
    hp: 6000,
    isBoss: true,
    liveCost: 8,
    name: "피츠랜돌프 공포 군주",
    size: 36,
    speed: 0.16,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    troopDamage: 420,
  },
  fallen_paladin: {
    abilities: [
      {
        chance: 0.3,
        desc: "어둠의 성스러운 불이 수비수를 태운다",
        duration: 3500,
        intensity: 18,
        name: "Corrupted Smite",
        type: "burn",
      },
      {
        chance: 1,
        desc: "타워 피해를 줄이는 타락한 존재",
        duration: 4000,
        intensity: 0.3,
        name: "Aura of Corruption",
        radius: 100,
        type: "tower_weaken",
      },
    ],
    armor: 0.4,
    bounty: 130,
    category: "dark_fantasy",
    color: "#4a3f6b",
    desc: "한때 아이비 리그의 고귀한 수비수였으나, 어둠의 야망에 의해 Princeton이 한때 대항했던 모든 것의 타락한 표본으로 뒤틀렸다. 그들의 어둠의 성스러운 불은 의로운 분노가 사악해진 것으로 수비수를 태우고, 타락한 존재는 근처 모든 타워의 피해를 줄인다. 전 동맹의 기술로 싸우는 비극적이고 강력한 적이다.",
    flying: false,
    hp: 2000,
    liveCost: 3,
    name: "Fallen Ivy Champion",
    size: 32,
    speed: 0.2,
    traits: ["armored", "magic_resist"],
    troopDamage: 110,
  },
  black_guard: {
    abilities: [
      {
        chance: 0.2,
        desc: "거대한 방패로 공격자를 막고 기절시킨다",
        duration: 1300,
        name: "Shield Wall",
        type: "stun",
      },
    ],
    armor: 0.45,
    bounty: 60,
    category: "dark_fantasy",
    color: "#1c1c2e",
    desc: "Prospect Garden 아래 깊숙이 단련된 칠흑 같은 강철의 정예 수호자들. 거대한 탑 방패는 공격자를 막고 기절시키며, 뚫을 수 없는 갑옷은 가장 강력한 관통 공격만 튕겨낸다. 종종 더 가치 있는 대상을 호위해 그들을 위해 의도된 피해를 흡수한다.",
    flying: false,
    hp: 900,
    name: "홀더 홀 파수꾼",
    size: 28,
    speed: 0.25,
    traits: ["armored"],
    troopDamage: 72,
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Dark Casters
  // =============================================================================
  lich: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 12_000,
        desc: "신비한 얼음에 타워를 봉인한다",
        duration: 3500,
        name: "비전 봉쇄",
        radius: 130,
        type: "tower_disable",
      },
      {
        chance: 0.3,
        desc: "얼리는 폭발이 근처 모두를 감속한다",
        duration: 3000,
        intensity: 0.4,
        name: "Frost Nova",
        radius: 100,
        type: "slow",
      },
    ],
    armor: 0.3,
    attackSpeed: 3000,
    bounty: 200,
    category: "dark_fantasy",
    color: "#4fc3f7",
    desc: "은퇴를 거부한 명예 교수 — 죽은 후에도 — 언데 데 대마법사로서 파괴적인 신비한 힘을 지휘한다. 서리 마법은 신비한 얼음에 타워를 봉인하고 얼리는 폭발은 광범위한 영역의 모든 것을 감속시킨다. 사무실에 숨겨진 영혼항아리는 파괴해야 한다 — 그렇지 않으면 매번 패배 후 단순히 재구성될 것이다.",
    flying: false,
    hp: 3000,
    isBoss: true,
    isRanged: true,
    liveCost: 5,
    name: "Emeritus Lich",
    projectileDamage: 336,
    range: 250,
    size: 34,
    speed: 0.12,
    summonCount: 2,
    summonType: "bone_mage",
    traits: ["ranged", "boss", "summoner", "magic_resist", "tower_debuffer"],
    troopDamage: 280,
  },
  wraith: {
    abilities: [
      {
        chance: 1,
        desc: "유령 같은 존재가 타워 메커니즘을 감속한다",
        duration: 2500,
        intensity: 0.25,
        name: "Spectral Chill",
        radius: 80,
        type: "tower_slow",
      },
    ],
    armor: 0.5,
    bounty: 55,
    category: "dark_fantasy",
    color: "#b39ddb",
    desc: "갑옷이 마법적으로 영적 형상에 입혀진 쓰러진 챔피언의 유령인 궁극의 영적 전사. 떠다니는 흉갑, 견갑, 왕관을 쓴 투구가 신비한 에너지의 실로 영적 몸에 연결되어 궤도를 돈다. 시려운 존재는 타워 메커니즘을 감속시키며, 어떤 물리 장벽도 한밤중 예배당의 끊임없는 조용한 전진을 막을 수 없다.",
    flying: true,
    hp: 450,
    liveCost: 2,
    name: "채플 망령",
    size: 24,
    speed: 0.5,
    targetsTroops: true,
    traits: ["flying", "magic_resist", "armored"],
    troopAttackSpeed: 1800,
    troopDamage: 45,
  },
  bone_mage: {
    abilities: [
      {
        chance: 0.25,
        desc: "타워에 저주를 걸어 효과를 줄인다",
        duration: 3000,
        intensity: 0.2,
        name: "뼈 저주",
        radius: 90,
        type: "tower_weaken",
      },
    ],
    armor: 0.1,
    attackSpeed: 2500,
    bounty: 45,
    category: "dark_fantasy",
    color: "#ce93d8",
    desc: "금지된 뼈술에 너무 깊이 들어간 해골 학자, 뼈 기반 전쟁의 대가로 부상한다. 저주는 광범위한 영역에서 타워 효과를 줄이고, 살아 움직이는 뼈 구조물은 방패와 투사체 역할을 한다. 하인이 아니라 마법을 죽여라 — 구조물은 주인이 쓰러지면 무너진다.",
    flying: false,
    hp: 380,
    isRanged: true,
    name: "McCosh Bone Scholar",
    projectileDamage: 65,
    range: 210,
    size: 24,
    speed: 0.24,
    traits: ["ranged", "magic_resist"],
  },
  dark_priest: {
    abilities: [
      {
        chance: 1,
        desc: "신성하지 않은 찬양이 타워 메커니즘을 방해한다",
        duration: 4000,
        intensity: 0.3,
        name: "Dark Prayer",
        radius: 100,
        type: "tower_slow",
      },
      {
        chance: 0.3,
        desc: "타락한 미아스마가 수비수를 중독시킨다",
        duration: 4500,
        intensity: 12,
        name: "마름병",
        radius: 80,
        type: "poison",
      },
    ],
    armor: 0.15,
    bounty: 65,
    category: "dark_fantasy",
    color: "#5c1a1a",
    desc: "대학 예배당 아래 그늘진 회랑에서 금지된 의식을 진행하는 파문된 사제들. 신성하지 않은 찬양은 맥동하는 오라에서 타워 메커니즘을 방해하고, 그들이 발산하는 타락한 미아스마는 수비수에게 시간에 걸쳐 중독을 입힌다. 종종 다른 언데 데와 함께 나타나 근처의 모든 어두운 생물의 힘을 증폭한다.",
    flying: false,
    hp: 600,
    name: "Cloister Heretic",
    size: 26,
    speed: 0.2,
    traits: ["tower_debuffer"],
    troopDamage: 55,
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Monstrous
  // =============================================================================
  revenant: {
    abilities: [
      {
        chance: 0.3,
        desc: "타는 듯한 분노가 근처 수비수를 태운다",
        duration: 3000,
        intensity: 15,
        name: "복수의 불꽃",
        type: "burn",
      },
      {
        chance: 0.2,
        desc: "격렬한 일격이 수비수를 기절시킨다",
        duration: 1200,
        name: "격노 강타",
        type: "stun",
      },
    ],
    armor: 0.25,
    bounty: 80,
    category: "dark_fantasy",
    color: "#c62828",
    desc: "최종 논쟁에서 진 자들의 복수심 강한 영혼들, 망령은 죽음 자체를 초월하는 분노로 타오른다. 타는 듯한 격노는 근처 수비수를 태우고 격렬한 일격은 명중 시 기절시키며, 근처에서 쓰러진 적이 있을 때마다 더 강해진다. 즉시 제거하지 않으면 통제 불능으로 눈덩이처럼 불어나는 자기 강화 위협이다.",
    flying: false,
    hp: 1100,
    liveCost: 2,
    name: "휘그-클리오 망자",
    size: 28,
    speed: 0.35,
    traits: ["fast"],
    troopDamage: 85,
  },
  abomination: {
    abilities: [
      {
        chance: 0.35,
        desc: "끔찍한 화학물질을 뿜어 근처 모두를 중독시킨다",
        duration: 5000,
        intensity: 18,
        name: "Toxic Spray",
        radius: 100,
        type: "poison",
      },
      {
        chance: 0.25,
        desc: "거대한 내리치기가 근처 모든 수비수를 기절시킨다",
        duration: 2000,
        name: "지면 강타",
        radius: 100,
        type: "stun",
      },
    ],
    aoeDamage: 504,
    aoeRadius: 110,
    armor: 0.35,
    bounty: 350,
    category: "dark_fantasy",
    color: "#4e342e",
    desc: "실패한 생물학 실험을 꿰매어 만든 그로테스크한 잡합 괴물, 흉물은 근처 모든 것을 중독시키는 끔찍한 화학물질을 뿜으며 앞으로 비틀거린다. 거대하고 맞지 않는 팔다리는 광범위한 영역에서 수비수를 기절시키는 내리치기 공격을 전달한다. Princeton의 어두운 역사에서 가장 disturbing한 창조물 — 일부 실험은 절대 실험실을 떠나서는 안 된다는 증거.",
    flying: false,
    hp: 8000,
    isBoss: true,
    liveCost: 8,
    name: "실험 구역 흉물",
    size: 42,
    speed: 0.1,
    traits: ["armored", "boss", "aoe_attack", "regenerating"],
    troopDamage: 476,
  },
  hellhound: {
    abilities: [
      {
        chance: 0.3,
        desc: "불타는 턱이 화상 상처를 남긴다",
        duration: 2500,
        intensity: 10,
        name: "Hellfire Bite",
        type: "burn",
      },
    ],
    armor: 0,
    bounty: 25,
    breakthrough: true,
    category: "dark_fantasy",
    color: "#ff6f00",
    desc: "포효하는 지옥불에 둘러싸인 거대한 알파 헬하운드, 근육질의 가시 능선 몸은 주변 공기를 뒤틀게 만드는 열을 발산한다. 끔찍한 속도로 방어를 가로질러 타오르며 불타는 턱은 물린 후 오래 지속되는 화상 상처를 남긴다. 정점 불꽃 포식자 — 전장에 있다면 다른 모든 것은 부차적이다.",
    flying: false,
    hp: 350,
    name: "타이거 홀로 지옥견",
    size: 22,
    speed: 0.65,
    traits: ["fast", "breakthrough"],
    troopDamage: 30,
  },
  doom_herald: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 14_000,
        desc: "전장을 어둠으로 뒤덮어 타워를 무력화한다",
        duration: 4500,
        name: "일식",
        radius: 150,
        type: "tower_disable",
      },
      {
        chance: 0.3,
        desc: "신성하지 않은 불꽃이 경로의 모든 것을 잡아먹는다",
        duration: 4500,
        intensity: 22,
        name: "암흑 불",
        radius: 100,
        type: "burn",
      },
      {
        chance: 0.2,
        desc: "파괴적인 폭발이 근처 모두를 기절시킨다",
        duration: 2500,
        name: "Doom Shockwave",
        radius: 120,
        type: "stun",
      },
    ],
    aoeDamage: 560,
    aoeRadius: 110,
    armor: 0.4,
    attackSpeed: 2500,
    bounty: 400,
    category: "dark_fantasy",
    color: "#311b92",
    desc: "재결합에 그림자와 불꽃의 날개를 달고 내려오는 어두운 대천사, 모든 축제의 끝을 알린다. 어둠의 담요는 광범위한 영역에서 타워를 무력화하고, 신성하지 않은 불꽃은 경로의 모든 것을 잡아먹으며, 파괴적인 폭발은 근처 모든 것을 기절시킨다. 파멸의 사자가 도착하면 파티는 끝난다 — 이것이 궁극의 어두운 판타지 위협이다.",
    flying: true,
    hp: 7000,
    isBoss: true,
    isRanged: true,
    liveCost: 10,
    name: "Reunions Doom Herald",
    projectileDamage: 364,
    range: 230,
    size: 40,
    speed: 0.18,
    targetsTroops: true,
    traits: ["flying", "boss", "aoe_attack", "tower_debuffer"],
    troopAttackSpeed: 2500,
    troopDamage: 392,
  },
  // =============================================================================
  // REGIONAL GIANT BOSSES - End-of-region mega bosses
  // =============================================================================
  titan_of_nassau: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 12_000,
        desc: "대지를 뒤흔드는 포효가 타워를 일시적으로 돌로 만든다",
        duration: 5000,
        name: "Petrifying Roar",
        radius: 160,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "거대한 발이 대지를 흔들어 모든 수비수를 기절시킨다",
        duration: 2800,
        name: "지진 발구르기",
        radius: 140,
        type: "stun",
      },
      {
        chance: 0.3,
        desc: "Princeton 불꽃이 입에서 쏟아져 모든 것을 태운다",
        duration: 5000,
        intensity: 30,
        name: "호랑이의 분노",
        radius: 120,
        type: "burn",
      },
    ],
    aoeDamage: 616,
    aoeRadius: 130,
    armor: 0.45,
    bounty: 600,
    category: "region_boss",
    color: "#e65100",
    desc: "Nassau Hall의 토대에서 깨어난 거대한 돌 호랑이. 고대 인동이 관절을 통해 신비한 에너지로 맥동하고, 눈은 Princeton 오렌지 불꽃으로 타오른다. 매 발걸음마다 대지가 떨린다.",
    flying: false,
    hp: 18_000,
    isBoss: true,
    liveCost: 15,
    name: "나소 거상",
    nativeRegion: "grassland",
    size: 52,
    speed: 0.08,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    troopDamage: 560,
  },
  swamp_leviathan: {
    abilities: [
      {
        chance: 0.35,
        desc: "부식성 학술적 공포가 근처 모두를 중독시킨다",
        duration: 6000,
        intensity: 25,
        name: "Thesis Bile",
        radius: 120,
        type: "poison",
      },
      {
        chance: 0.25,
        desc: "거대한 꼬리 휘두르기가 근처 모든 수비수를 기절시킨다",
        duration: 2200,
        name: "Tail Crush",
        radius: 130,
        type: "stun",
      },
      {
        chance: 1,
        desc: "학술적 불확실성의 안개가 타워를 약화시킨다",
        duration: 5000,
        intensity: 0.35,
        name: "Miasma of Doubt",
        radius: 140,
        type: "tower_weaken",
      },
    ],
    aoeDamage: 560,
    aoeRadius: 120,
    armor: 0.35,
    bounty: 550,
    category: "region_boss",
    color: "#1b5e20",
    desc: "학술적 늪에서 솟아오른 꿈틀대는 다중 머리 뱀류 공포. 각 머리는 끝낼 수 없는 한 장을 나타낸다 — 하나를 베면 다른 논쟁이 떠오른다. 모든 입에서 독성 학술적 쓸개가 떨어진다.",
    flying: false,
    hp: 16_000,
    isBoss: true,
    liveCost: 12,
    name: "The Thesis Hydra",
    nativeRegion: "swamp",
    size: 50,
    speed: 0.1,
    summonCount: 2,
    summonType: "bog_creature",
    traits: ["armored", "boss", "aoe_attack", "regenerating", "summoner"],
    troopDamage: 504,
  },
  sphinx_guardian: {
    abilities: [
      {
        chance: 0.15,
        cooldown: 14_000,
        desc: "타워 로직을 얼려버리는 불가능한 질문을 던진다",
        duration: 5500,
        name: "풀 수 없는 수수께끼",
        radius: 170,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "관통하는 시선이 그것과 마주치는 모두를 마비시킨다",
        duration: 3000,
        name: "Judgmental Gaze",
        radius: 150,
        type: "stun",
      },
      {
        chance: 1,
        desc: "고대 저주가 타워로 훈련받은 것을 잊게 만든다",
        duration: 5500,
        intensity: 0.4,
        name: "Curse of Ignorance",
        radius: 160,
        type: "tower_weaken",
      },
      {
        chance: 1,
        desc: "주변의 시간을 왜곡해 근처 모두를 감속한다",
        duration: 4000,
        intensity: 0.5,
        name: "Time Dilation",
        radius: 130,
        type: "slow",
      },
    ],
    aoeDamage: 672,
    aoeRadius: 140,
    armor: 0.5,
    bounty: 700,
    category: "region_boss",
    color: "#f9a825",
    desc: "사암과 황금으로 깎은 고대 거대한 스핑크스. 답 없는 수수께끼를 던져 수비수들의 정신을 무력화한다. 그 시선만으로도 타워를 산산조각 낼 수 있다. 절대 준비할 수 없는 궁극의 시험이다.",
    flying: false,
    hp: 20_000,
    isBoss: true,
    liveCost: 15,
    name: "The Midterm Sphinx",
    nativeRegion: "desert",
    size: 54,
    speed: 0.07,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer", "magic_resist"],
    troopDamage: 616,
  },
  frost_colossus: {
    abilities: [
      {
        chance: 1,
        desc: "얼리는 오라가 모든 것을 기어가게 만든다",
        duration: 5000,
        intensity: 0.55,
        name: "절대 영도",
        radius: 150,
        type: "slow",
      },
      {
        chance: 0.15,
        cooldown: 11_000,
        desc: "타워를 단단한 얼음에 가둔다",
        duration: 4500,
        name: "Flash Freeze",
        radius: 140,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "눈사태처럼 주먹을 내리쳐 모두를 기절시킨다",
        duration: 2500,
        name: "Glacier Slam",
        radius: 130,
        type: "stun",
      },
      {
        chance: 1,
        desc: "영구적인 냉기가 타워 메커니즘을 크게 감속한다",
        duration: 6000,
        intensity: 0.45,
        name: "Permafrost",
        radius: 160,
        type: "tower_slow",
      },
    ],
    aoeDamage: 588,
    aoeRadius: 130,
    armor: 0.55,
    bounty: 650,
    category: "region_boss",
    color: "#4dd0e1",
    desc: "잔혹한 1월 추위에서 태어난 거대한 결정성 얼음 거인. 반투명 몸 안에서 눈보라가 분노하고 지나가는 모든 표면이 꽁꽁 얼어붙는다. 겨울의 잔혹함의 화신.",
    flying: false,
    hp: 17_000,
    isBoss: true,
    liveCost: 12,
    name: "The January Titan",
    nativeRegion: "winter",
    size: 52,
    speed: 0.09,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    troopDamage: 588,
  },
  inferno_wyrm: {
    abilities: [
      {
        chance: 0.35,
        desc: "용해된 불을 분출해 보이는 모든 것을 그을린다",
        duration: 6000,
        intensity: 35,
        name: "Magma Eruption",
        radius: 150,
        type: "burn",
      },
      {
        chance: 0.15,
        cooldown: 13_000,
        desc: "극심한 열이 타워 멜트다운을 일으킨다",
        duration: 5000,
        name: "화산 과부하",
        radius: 160,
        type: "tower_disable",
      },
      {
        chance: 0.25,
        desc: "몸을 대지에 내리쳐 모든 수비수를 기절시킨다",
        duration: 3000,
        name: "Tectonic Shatter",
        radius: 140,
        type: "stun",
      },
      {
        chance: 1,
        desc: "강렬한 열이 현실을 왜곡해 타워 효과를 줄인다",
        duration: 5500,
        intensity: 0.4,
        name: "열 왜곡",
        radius: 170,
        type: "tower_weaken",
      },
    ],
    aoeDamage: 784,
    aoeRadius: 150,
    armor: 0.4,
    bounty: 800,
    category: "region_boss",
    color: "#d50000",
    desc: "화산 깊숙이에서 분출하는 거대한 용암 뱀. 용해된 비늘이 액체 불을 떨어뜨리고, 몸은 전장을 가로질러 늘어나며, 공기 자체가 그 뒤에서 불이 붙는다. 학술적 번아웃의 궁극적 화신.",
    flying: false,
    hp: 22_000,
    isBoss: true,
    liveCost: 20,
    name: "The Burnout Wyrm",
    nativeRegion: "volcanic",
    size: 56,
    speed: 0.06,
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer", "regenerating"],
    troopDamage: 700,
  },
};

// =============================================================================
// ENEMY TRAIT DISPLAY METADATA
// =============================================================================

export interface EnemyTraitMeta {
  label: string;
  color: string;
  desc: string;
  pillColor: string;
}

export const ENEMY_TRAIT_META: Record<EnemyTrait, EnemyTraitMeta> = {
  aoe_attack: {
    color: "text-orange-400",
    desc: "공격이 여러 대상을 명중한다",
    label: "광역",
    pillColor: "bg-orange-900/60 text-orange-300 border-orange-700/40",
  },
  armored: {
    color: "text-amber-400",
    desc: "받는 피해가 줄어든다",
    label: "장갑",
    pillColor: "bg-blue-900/60 text-blue-300 border-blue-700/40",
  },
  boss: {
    color: "text-red-400",
    desc: "체력이 높은 강력한 정예 적",
    label: "보스",
    pillColor: "bg-red-900/60 text-red-300 border-red-700/40",
  },
  breakthrough: {
    color: "text-sky-400",
    desc: "병영 병사를 멈추지 않고 지나간다",
    label: "Breakthrough",
    pillColor: "bg-amber-900/60 text-amber-300 border-amber-700/40",
  },
  fast: {
    color: "text-yellow-400",
    desc: "일반 적보다 빠르게 이동한다",
    label: "빠른",
    pillColor: "bg-yellow-900/60 text-yellow-300 border-yellow-700/40",
  },
  flying: {
    color: "text-cyan-400",
    desc: "지상 장애물을 무시하며 특정 타워에만 맞는다",
    label: "비행",
    pillColor: "bg-cyan-900/60 text-cyan-300 border-cyan-700/40",
  },
  magic_resist: {
    color: "text-blue-400",
    desc: "마법 공격의 피해가 줄어든다",
    label: "Magic Resist",
    pillColor: "bg-indigo-900/60 text-indigo-300 border-indigo-700/40",
  },
  ranged: {
    color: "text-green-400",
    desc: "거리에서 공격한다",
    label: "원거리",
    pillColor: "bg-green-900/60 text-green-300 border-green-700/40",
  },
  regenerating: {
    color: "text-green-400",
    desc: "시간이 지나며 천천히 체력을 회복한다",
    label: "재생",
    pillColor: "bg-emerald-900/60 text-emerald-300 border-emerald-700/40",
  },
  summoner: {
    color: "text-purple-400",
    desc: "추가 적을 소환할 수 있다",
    label: "소환형",
    pillColor: "bg-purple-900/60 text-purple-300 border-purple-700/40",
  },
  tower_debuffer: {
    color: "text-rose-400",
    desc: "타워를 약화시키거나 무력화할 수 있다",
    label: "Debuffer",
    pillColor: "bg-rose-900/60 text-rose-300 border-rose-700/40",
  },
};

// =============================================================================
// ENEMY ABILITY TYPE DISPLAY METADATA
// =============================================================================

export interface EnemyAbilityMeta {
  color: string;
  bgColor: string;
}

export const ENEMY_ABILITY_META: Record<
  EnemyAbilityType | "default",
  EnemyAbilityMeta
> = {
  burn: {
    bgColor: "bg-orange-950/60 border-orange-800/50",
    color: "text-orange-400",
  },
  default: {
    bgColor: "bg-gray-950/60 border-gray-800/50",
    color: "text-gray-400",
  },
  poison: {
    bgColor: "bg-green-950/60 border-green-800/50",
    color: "text-green-400",
  },
  slow: {
    bgColor: "bg-cyan-950/60 border-cyan-800/50",
    color: "text-cyan-400",
  },
  stun: {
    bgColor: "bg-yellow-950/60 border-yellow-800/50",
    color: "text-yellow-400",
  },
  tower_blind: {
    bgColor: "bg-purple-950/60 border-purple-800/50",
    color: "text-purple-400",
  },
  tower_disable: {
    bgColor: "bg-rose-950/60 border-rose-800/50",
    color: "text-rose-400",
  },
  tower_slow: {
    bgColor: "bg-blue-950/60 border-blue-800/50",
    color: "text-blue-400",
  },
  tower_weaken: {
    bgColor: "bg-red-950/60 border-red-800/50",
    color: "text-red-400",
  },
};

// =============================================================================
// ENEMY CATEGORY DISPLAY METADATA
// =============================================================================

export interface EnemyCategoryMeta {
  name: string;
  desc: string;
  color: string;
  bgColor: string;
}

export const ENEMY_CATEGORY_META: Record<EnemyCategory, EnemyCategoryMeta> = {
  academic: {
    bgColor: "bg-purple-950/50 border-purple-800/40",
    color: "text-purple-400",
    desc: "학술 진도와 이정표",
    name: "academic",
  },
  campus: {
    bgColor: "bg-amber-950/50 border-amber-800/40",
    color: "text-amber-400",
    desc: "캠퍼스 이벤트와 활동",
    name: "Campus Life",
  },
  dark_fantasy: {
    bgColor: "bg-violet-950/50 border-violet-800/40",
    color: "text-violet-400",
    desc: "언데, 해골, 어두운 판타지 적",
    name: "다크 판타지",
  },
  desert: {
    bgColor: "bg-yellow-950/50 border-yellow-800/40",
    color: "text-yellow-600",
    desc: "사막 바이옴 생물",
    name: "사막",
  },
  flying: {
    bgColor: "bg-cyan-950/50 border-cyan-800/40",
    color: "text-cyan-400",
    desc: "지상 장애물을 우회하는 공중 위협",
    name: "비행",
  },
  forest: {
    bgColor: "bg-emerald-950/50 border-emerald-800/40",
    color: "text-emerald-400",
    desc: "숲 바이옴 생물",
    name: "숲",
  },
  insectoid: {
    bgColor: "bg-amber-950/50 border-amber-900/40",
    color: "text-amber-700",
    desc: "곤충과 거미류",
    name: "Insectoid",
  },
  ranged: {
    bgColor: "bg-green-950/50 border-green-800/40",
    color: "text-green-400",
    desc: "거리에서 공격한다",
    name: "원거리",
  },
  region_boss: {
    bgColor: "bg-red-950/50 border-red-800/40",
    color: "text-red-400",
    desc: "지역별 최종 메가 보스",
    name: "지역 보스",
  },
  swamp: {
    bgColor: "bg-lime-950/50 border-lime-800/40",
    color: "text-lime-400",
    desc: "늪 바이옴 생물",
    name: "늪지",
  },
  volcanic: {
    bgColor: "bg-orange-950/50 border-orange-800/40",
    color: "text-orange-400",
    desc: "불과 용암 바이옴 생물",
    name: "화산",
  },
  winter: {
    bgColor: "bg-sky-950/50 border-sky-800/40",
    color: "text-sky-400",
    desc: "겨울과 서리 바이옴 생물",
    name: "겨울",
  },
};

export const ENEMY_CATEGORY_ORDER: EnemyCategory[] = [
  "academic",
  "campus",
  "ranged",
  "dark_fantasy",
  "forest",
  "swamp",
  "desert",
  "winter",
  "volcanic",
  "flying",
  "insectoid",
  "region_boss",
];

export const ENEMY_CATEGORY_ACCENTS: Record<EnemyCategory, string> = {
  academic: "#c084fc",
  campus: "#f59e0b",
  dark_fantasy: "#a78bfa",
  desert: "#ca8a04",
  flying: "#22d3ee",
  forest: "#34d399",
  insectoid: "#d97706",
  ranged: "#4ade80",
  region_boss: "#f87171",
  swamp: "#84cc16",
  volcanic: "#fb923c",
  winter: "#38bdf8",
};

const CATEGORY_NATIVE_REGION: Partial<Record<EnemyCategory, MapTheme>> = {
  desert: "desert",
  forest: "grassland",
  swamp: "swamp",
  volcanic: "volcanic",
  winter: "winter",
};

export function getEnemyNativeRegion(type: EnemyType): MapTheme | null {
  const data = ENEMY_DATA[type];
  if (!data) {
    return null;
  }
  if (data.nativeRegion) {
    return data.nativeRegion;
  }
  const cat = data.category;
  if (cat && CATEGORY_NATIVE_REGION[cat]) {
    return CATEGORY_NATIVE_REGION[cat]!;
  }
  return null;
}

const REGIONAL_VARIANT_THEMES: MapTheme[] = [
  "swamp",
  "desert",
  "winter",
  "volcanic",
];

const REGIONAL_VARIANT_TYPES = new Set<EnemyType>([
  // Shared overlay enemies (academic)
  "frosh",
  "2학년",
  "3학년",
  "4학년",
  "gradstudent",
  // Ranged
  "archer",
  "mage",
  "crossbowman",
  "warlock",
  "hexer",
  // Flying
  "harpy",
  "wyvern",
  // Undead / dark fantasy (also have dedicated palettes for plaguebearer)
  "specter",
  "berserker",
  "necromancer",
  "shadow_knight",
  "cultist",
  "plaguebearer",
  // Elemental (infernal has dedicated palette)
  "banshee",
  "assassin",
  "infernal",
  // Campus / forest
  "athlete",
  "tiger_fan",
  "마스코트",
  // Dedicated palette enemies
  "ancient_ent",
]);

export function hasRegionalVariants(type: EnemyType): boolean {
  return REGIONAL_VARIANT_TYPES.has(type);
}

export function getRegionalVariantThemes(): MapTheme[] {
  return REGIONAL_VARIANT_THEMES;
}

const THEME_LABELS: Record<MapTheme, string> = {
  desert: "사막",
  grassland: "초원",
  swamp: "늪지",
  volcanic: "화산",
  winter: "겨울",
};

export function getThemeLabel(theme: MapTheme): string {
  return THEME_LABELS[theme];
}

export function groupEnemiesByCategory(
  enemyTypes: EnemyType[]
): Record<EnemyCategory, EnemyType[]> {
  const grouped: Record<EnemyCategory, EnemyType[]> = {
    academic: [],
    campus: [],
    dark_fantasy: [],
    desert: [],
    flying: [],
    forest: [],
    insectoid: [],
    ranged: [],
    region_boss: [],
    swamp: [],
    volcanic: [],
    winter: [],
  };
  for (const type of enemyTypes) {
    const enemy = ENEMY_DATA[type];
    const category = enemy.category || "campus";
    grouped[category].push(type);
  }
  return grouped;
}
