import type { TroopData, TroopType } from "../types";

// Troop data - includes "elite" for Level 3 station
export const TROOP_DATA: Record<TroopType, TroopData> = {
  armored: {
    attackSpeed: 1000,
    color: "#708090",
    damage: 25,
    desc: "판금 갑옷을 입은 파수꾼이 플랜지 메이스와 히터 실드를 들고 있다. 약한 병사를 쓰러뜨릴 만한 공격을 흡수하도록 만들어졌다.",
    hp: 1100,
    name: "장갑병",
  },
  cavalry: {
    attackSpeed: 1100,
    color: "#daa520",
    damage: 55,
    desc: "광채나는 갑옷을 입은 왕실 전투마 위의 우레 같은 창기사. 돌격 시 파괴적이며 거의 밀어낼 수 없다.",
    hp: 1800,
    isMounted: true,
    name: "기병대",
  },
  centaur: {
    attackSpeed: 700,
    canTargetFlying: true,
    color: "#8b4513",
    damage: 45,
    desc: "강력한 군마를 탄 황금빛 전투 궁수. 비행 중인 대상도 맞힐 수 있는 정밀한 일제 사격을 쏜다.",
    hp: 1200,
    isMounted: true,
    isRanged: true,
    name: "켄타우로스",
    range: 280,
  },
  elite: {
    attackSpeed: 900,
    color: "#c0c0c0",
    damage: 35,
    desc: "프린스턴 문장을 단 금빛 갑옷의 베테랑 할버디어. 단련된 사거리와 정밀함으로 공격한다.",
    hp: 1400,
    name: "정예 근위대",
  },
  footsoldier: {
    attackSpeed: 1100,
    color: "#6b8e23",
    damage: 20,
    desc: "글라디우스와 스쿠툼 방패를 든 불량한 수비대 신병. 낡은 장비에도 라인을 지키겠다는 결의.",
    hp: 700,
    name: "보병",
  },
  hexling: {
    attackSpeed: 880,
    canTargetFlying: true,
    color: "#c026d3",
    damage: 34,
    desc: "원거리에서 비술 화살을 던지는 악의의 깜박이는 영혼. 지상과 공중의 적 모두를 공격할 수 있다.",
    hp: 1050,
    isRanged: true,
    name: "저주 정령",
    range: 240,
  },
  hexseer: {
    attackSpeed: 720,
    canTargetFlying: true,
    color: "#f472b6",
    damage: 58,
    desc: "강력한 영혼으로 엮어진 승천한 저주 시전자. 그 비술 연사 사격은 어떤 하급 영혼보다도 멀리, 강하게 도달한다.",
    hp: 1500,
    isRanged: true,
    name: "저주 예언자",
    range: 290,
  },
  knight: {
    attackSpeed: 850,
    color: "#c0c0c0",
    damage: 38,
    desc: "각각 독특하게 제작된 갑옷과 무기를 갖춘 풀 플레이트의 챔피언. 수비대의 최고이자 가장 무시무시한 자들이다.",
    hp: 1000,
    name: "기사",
  },
  reinforcement: {
    attackSpeed: 1000,
    color: "#a78bfa",
    damage: 30,
    desc: "전장 마법으로 소환된 비전 전사. 각자 독특하게 마법이 걸린 갑옷과 투구로 등장한다. 주문 업그레이드로 더 강해진다.",
    hp: 1000,
    name: "증원",
  },
  rowing: {
    attackSpeed: 1000,
    color: "#8b5cf6",
    damage: 45,
    desc: "보라색 저주에 의해 다시 끌려온 거대한 유령. 거의 아무도 감당할 수 없는, 거세고 뼈를 으스러뜨리는 힘으로 휘두른다.",
    hp: 1700,
    name: "저주 노잡이",
  },
  thesis: {
    attackSpeed: 750,
    color: "#a855f7",
    damage: 55,
    desc: "저주 마법에 묶이고 정예 영혼으로 만들어진 되살아난 학자. 금단의 지식을 파괴적인 공격으로 끌어낸다.",
    hp: 1400,
    name: "저주 학자",
  },
  turret: {
    attackSpeed: 800,
    color: "#f59e0b",
    damage: 35,
    desc: "근처 위협에 볼트를 비처럼 내리는 기계식 공성 배치. 배치되면 움직이지 않지만 끊임없이 공격한다.",
    hp: 800,
    isRanged: true,
    isStationary: true,
    name: "방어 포탑",
    range: 140,
  },
};
